export interface Pokemon {
  id: string;
  name: string;
  nameEn: string;
  soundPath: string;
  imagePath: string;
}

export const POKEMON_LIST: Pokemon[] = [
  { id: '001', name: 'フシギダネ', nameEn: 'Bulbasaur', soundPath: '/sounds/001.wav', imagePath: '/images/001.png' },
  { id: '002', name: 'フシギソウ', nameEn: 'Ivysaur', soundPath: '/sounds/002.wav', imagePath: '/images/002.png' },
  { id: '003', name: 'フシギバナ', nameEn: 'Venusaur', soundPath: '/sounds/003.wav', imagePath: '/images/003.png' },
  { id: '004', name: 'ヒトカゲ', nameEn: 'Charmander', soundPath: '/sounds/004.wav', imagePath: '/images/004.png' },
  { id: '005', name: 'リザード', nameEn: 'Charmeleon', soundPath: '/sounds/005.wav', imagePath: '/images/005.png' },
  { id: '006', name: 'リザードン', nameEn: 'Charizard', soundPath: '/sounds/006.wav', imagePath: '/images/006.png' },
  { id: '007', name: 'ゼニガメ', nameEn: 'Squirtle', soundPath: '/sounds/007.wav', imagePath: '/images/007.png' },
  { id: '008', name: 'カメール', nameEn: 'Wartortle', soundPath: '/sounds/008.wav', imagePath: '/images/008.png' },
  { id: '009', name: 'カメックス', nameEn: 'Blastoise', soundPath: '/sounds/009.wav', imagePath: '/images/009.png' },
  { id: '010', name: 'キャタピー', nameEn: 'Caterpie', soundPath: '/sounds/010.wav', imagePath: '/images/010.png' },
  { id: '011', name: 'トランセル', nameEn: 'Metapod', soundPath: '/sounds/011.wav', imagePath: '/images/011.png' },
  { id: '012', name: 'バタフリー', nameEn: 'Butterfree', soundPath: '/sounds/012.wav', imagePath: '/images/012.png' },
  { id: '013', name: 'ビードル', nameEn: 'Weedle', soundPath: '/sounds/013.wav', imagePath: '/images/013.png' },
  { id: '014', name: 'コクーン', nameEn: 'Kakuna', soundPath: '/sounds/014.wav', imagePath: '/images/014.png' },
  { id: '015', name: 'スピアー', nameEn: 'Beedrill', soundPath: '/sounds/015.wav', imagePath: '/images/015.png' },
  { id: '016', name: 'ポッポ', nameEn: 'Pidgey', soundPath: '/sounds/016.wav', imagePath: '/images/016.png' },
  { id: '017', name: 'ピジョン', nameEn: 'Pidgeotto', soundPath: '/sounds/017.wav', imagePath: '/images/017.png' },
  { id: '018', name: 'ピジョット', nameEn: 'Pidgeot', soundPath: '/sounds/018.wav', imagePath: '/images/018.png' },
  { id: '019', name: 'コラッタ', nameEn: 'Rattata', soundPath: '/sounds/019.wav', imagePath: '/images/019.png' },
  { id: '020', name: 'ラッタ', nameEn: 'Raticate', soundPath: '/sounds/020.wav', imagePath: '/images/020.png' },
  { id: '021', name: 'オニスズメ', nameEn: 'Spearow', soundPath: '/sounds/021.wav', imagePath: '/images/021.png' },
  { id: '022', name: 'オニドリル', nameEn: 'Fearow', soundPath: '/sounds/022.wav', imagePath: '/images/022.png' },
  { id: '023', name: 'アーボ', nameEn: 'Ekans', soundPath: '/sounds/023.wav', imagePath: '/images/023.png' },
  { id: '024', name: 'アーボック', nameEn: 'Arbok', soundPath: '/sounds/024.wav', imagePath: '/images/024.png' },
  { id: '025', name: 'ピカチュウ', nameEn: 'Pikachu', soundPath: '/sounds/025.wav', imagePath: '/images/025.png' },
  { id: '026', name: 'ライチュウ', nameEn: 'Raichu', soundPath: '/sounds/026.wav', imagePath: '/images/026.png' },
  { id: '027', name: 'サンド', nameEn: 'Sandshrew', soundPath: '/sounds/027.wav', imagePath: '/images/027.png' },
  { id: '028', name: 'サンドパン', nameEn: 'Sandslash', soundPath: '/sounds/028.wav', imagePath: '/images/028.png' },
  { id: '029', name: 'ニドラン♀', nameEn: 'Nidoran♀', soundPath: '/sounds/029.wav', imagePath: '/images/029.png' },
  { id: '030', name: 'ニドリーナ', nameEn: 'Nidorina', soundPath: '/sounds/030.wav', imagePath: '/images/030.png' },
  { id: '031', name: 'ニドクイン', nameEn: 'Nidoqueen', soundPath: '/sounds/031.wav', imagePath: '/images/031.png' },
  { id: '032', name: 'ニドラン♂', nameEn: 'Nidoran♂', soundPath: '/sounds/032.wav', imagePath: '/images/032.png' },
  { id: '033', name: 'ニドリーノ', nameEn: 'Nidorino', soundPath: '/sounds/033.wav', imagePath: '/images/033.png' },
  { id: '034', name: 'ニドキング', nameEn: 'Nidoking', soundPath: '/sounds/034.wav', imagePath: '/images/034.png' },
  { id: '035', name: 'ピッピ', nameEn: 'Clefairy', soundPath: '/sounds/035.wav', imagePath: '/images/035.png' },
  { id: '036', name: 'ピクシー', nameEn: 'Clefable', soundPath: '/sounds/036.wav', imagePath: '/images/036.png' },
  { id: '037', name: 'ロコン', nameEn: 'Vulpix', soundPath: '/sounds/037.wav', imagePath: '/images/037.png' },
  { id: '038', name: 'キュウコン', nameEn: 'Ninetales', soundPath: '/sounds/038.wav', imagePath: '/images/038.png' },
  { id: '039', name: 'プリン', nameEn: 'Jigglypuff', soundPath: '/sounds/039.wav', imagePath: '/images/039.png' },
  { id: '040', name: 'プクリン', nameEn: 'Wigglytuff', soundPath: '/sounds/040.wav', imagePath: '/images/040.png' },
  { id: '041', name: 'ズバット', nameEn: 'Zubat', soundPath: '/sounds/041.wav', imagePath: '/images/041.png' },
  { id: '042', name: 'ゴルバット', nameEn: 'Golbat', soundPath: '/sounds/042.wav', imagePath: '/images/042.png' },
  { id: '043', name: 'ナゾノクサ', nameEn: 'Oddish', soundPath: '/sounds/043.wav', imagePath: '/images/043.png' },
  { id: '044', name: 'クサイハナ', nameEn: 'Gloom', soundPath: '/sounds/044.wav', imagePath: '/images/044.png' },
  { id: '045', name: 'ラフレシア', nameEn: 'Vileplume', soundPath: '/sounds/045.wav', imagePath: '/images/045.png' },
  { id: '046', name: 'パラス', nameEn: 'Paras', soundPath: '/sounds/046.wav', imagePath: '/images/046.png' },
  { id: '047', name: 'パラセクト', nameEn: 'Parasect', soundPath: '/sounds/047.wav', imagePath: '/images/047.png' },
  { id: '048', name: 'コンパン', nameEn: 'Venonat', soundPath: '/sounds/048.wav', imagePath: '/images/048.png' },
  { id: '049', name: 'モルフォン', nameEn: 'Venomoth', soundPath: '/sounds/049.wav', imagePath: '/images/049.png' },
  { id: '050', name: 'ディグダ', nameEn: 'Diglett', soundPath: '/sounds/050.wav', imagePath: '/images/050.png' },
  { id: '051', name: 'ダグトリオ', nameEn: 'Dugtrio', soundPath: '/sounds/051.wav', imagePath: '/images/051.png' },
  { id: '052', name: 'ニャース', nameEn: 'Meowth', soundPath: '/sounds/052.wav', imagePath: '/images/052.png' },
  { id: '053', name: 'ペルシアン', nameEn: 'Persian', soundPath: '/sounds/053.wav', imagePath: '/images/053.png' },
  { id: '054', name: 'コダック', nameEn: 'Psyduck', soundPath: '/sounds/054.wav', imagePath: '/images/054.png' },
  { id: '055', name: 'ゴルダック', nameEn: 'Golduck', soundPath: '/sounds/055.wav', imagePath: '/images/055.png' },
  { id: '056', name: 'マンキー', nameEn: 'Mankey', soundPath: '/sounds/056.wav', imagePath: '/images/056.png' },
  { id: '057', name: 'オコリザル', nameEn: 'Primeape', soundPath: '/sounds/057.wav', imagePath: '/images/057.png' },
  { id: '058', name: 'ガーディ', nameEn: 'Growlithe', soundPath: '/sounds/058.wav', imagePath: '/images/058.png' },
  { id: '059', name: 'ウインディ', nameEn: 'Arcanine', soundPath: '/sounds/059.wav', imagePath: '/images/059.png' },
  { id: '060', name: 'ニョロモ', nameEn: 'Poliwag', soundPath: '/sounds/060.wav', imagePath: '/images/060.png' },
  { id: '061', name: 'ニョロゾ', nameEn: 'Poliwhirl', soundPath: '/sounds/061.wav', imagePath: '/images/061.png' },
  { id: '062', name: 'ニョロボン', nameEn: 'Poliwrath', soundPath: '/sounds/062.wav', imagePath: '/images/062.png' },
  { id: '063', name: 'ケーシィ', nameEn: 'Abra', soundPath: '/sounds/063.wav', imagePath: '/images/063.png' },
  { id: '064', name: 'ユンゲラー', nameEn: 'Kadabra', soundPath: '/sounds/064.wav', imagePath: '/images/064.png' },
  { id: '065', name: 'フーディン', nameEn: 'Alakazam', soundPath: '/sounds/065.wav', imagePath: '/images/065.png' },
  { id: '066', name: 'ワンリキー', nameEn: 'Machop', soundPath: '/sounds/066.wav', imagePath: '/images/066.png' },
  { id: '067', name: 'ゴーリキー', nameEn: 'Machoke', soundPath: '/sounds/067.wav', imagePath: '/images/067.png' },
  { id: '068', name: 'カイリキー', nameEn: 'Machamp', soundPath: '/sounds/068.wav', imagePath: '/images/068.png' },
  { id: '069', name: 'マダツボミ', nameEn: 'Bellsprout', soundPath: '/sounds/069.wav', imagePath: '/images/069.png' },
  { id: '070', name: 'ウツドン', nameEn: 'Weepinbell', soundPath: '/sounds/070.wav', imagePath: '/images/070.png' },
  { id: '071', name: 'ウツボット', nameEn: 'Victreebel', soundPath: '/sounds/071.wav', imagePath: '/images/071.png' },
  { id: '072', name: 'メノクラゲ', nameEn: 'Tentacool', soundPath: '/sounds/072.wav', imagePath: '/images/072.png' },
  { id: '073', name: 'ドククラゲ', nameEn: 'Tentacruel', soundPath: '/sounds/073.wav', imagePath: '/images/073.png' },
  { id: '074', name: 'イシツブテ', nameEn: 'Geodude', soundPath: '/sounds/074.wav', imagePath: '/images/074.png' },
  { id: '075', name: 'ゴローン', nameEn: 'Graveler', soundPath: '/sounds/075.wav', imagePath: '/images/075.png' },
  { id: '076', name: 'ゴローニャ', nameEn: 'Golem', soundPath: '/sounds/076.wav', imagePath: '/images/076.png' },
  { id: '077', name: 'ポニータ', nameEn: 'Ponyta', soundPath: '/sounds/077.wav', imagePath: '/images/077.png' },
  { id: '078', name: 'ギャロップ', nameEn: 'Rapidash', soundPath: '/sounds/078.wav', imagePath: '/images/078.png' },
  { id: '079', name: 'ヤドン', nameEn: 'Slowpoke', soundPath: '/sounds/079.wav', imagePath: '/images/079.png' },
  { id: '080', name: 'ヤドラン', nameEn: 'Slowbro', soundPath: '/sounds/080.wav', imagePath: '/images/080.png' },
  { id: '081', name: 'コイル', nameEn: 'Magnemite', soundPath: '/sounds/081.wav', imagePath: '/images/081.png' },
  { id: '082', name: 'レアコイル', nameEn: 'Magneton', soundPath: '/sounds/082.wav', imagePath: '/images/082.png' },
  { id: '083', name: 'カモネギ', nameEn: "Farfetch'd", soundPath: '/sounds/083.wav', imagePath: '/images/083.png' },
  { id: '084', name: 'ドードー', nameEn: 'Doduo', soundPath: '/sounds/084.wav', imagePath: '/images/084.png' },
  { id: '085', name: 'ドードリオ', nameEn: 'Dodrio', soundPath: '/sounds/085.wav', imagePath: '/images/085.png' },
  { id: '086', name: 'パウワウ', nameEn: 'Seel', soundPath: '/sounds/086.wav', imagePath: '/images/086.png' },
  { id: '087', name: 'ジュゴン', nameEn: 'Dewgong', soundPath: '/sounds/087.wav', imagePath: '/images/087.png' },
  { id: '088', name: 'ベトベター', nameEn: 'Grimer', soundPath: '/sounds/088.wav', imagePath: '/images/088.png' },
  { id: '089', name: 'ベトベトン', nameEn: 'Muk', soundPath: '/sounds/089.wav', imagePath: '/images/089.png' },
  { id: '090', name: 'シェルダー', nameEn: 'Shellder', soundPath: '/sounds/090.wav', imagePath: '/images/090.png' },
  { id: '091', name: 'パルシェン', nameEn: 'Cloyster', soundPath: '/sounds/091.wav', imagePath: '/images/091.png' },
  { id: '092', name: 'ゴース', nameEn: 'Gastly', soundPath: '/sounds/092.wav', imagePath: '/images/092.png' },
  { id: '093', name: 'ゴースト', nameEn: 'Haunter', soundPath: '/sounds/093.wav', imagePath: '/images/093.png' },
  { id: '094', name: 'ゲンガー', nameEn: 'Gengar', soundPath: '/sounds/094.wav', imagePath: '/images/094.png' },
  { id: '095', name: 'イワーク', nameEn: 'Onix', soundPath: '/sounds/095.wav', imagePath: '/images/095.png' },
  { id: '096', name: 'スリープ', nameEn: 'Drowzee', soundPath: '/sounds/096.wav', imagePath: '/images/096.png' },
  { id: '097', name: 'スリーパー', nameEn: 'Hypno', soundPath: '/sounds/097.wav', imagePath: '/images/097.png' },
  { id: '098', name: 'クラブ', nameEn: 'Krabby', soundPath: '/sounds/098.wav', imagePath: '/images/098.png' },
  { id: '099', name: 'キングラー', nameEn: 'Kingler', soundPath: '/sounds/099.wav', imagePath: '/images/099.png' },
  { id: '100', name: 'ビリリダマ', nameEn: 'Voltorb', soundPath: '/sounds/100.wav', imagePath: '/images/100.png' },
  { id: '101', name: 'マルマイン', nameEn: 'Electrode', soundPath: '/sounds/101.wav', imagePath: '/images/101.png' },
  { id: '102', name: 'タマタマ', nameEn: 'Exeggcute', soundPath: '/sounds/102.wav', imagePath: '/images/102.png' },
  { id: '103', name: 'ナッシー', nameEn: 'Exeggutor', soundPath: '/sounds/103.wav', imagePath: '/images/103.png' },
  { id: '104', name: 'カラカラ', nameEn: 'Cubone', soundPath: '/sounds/104.wav', imagePath: '/images/104.png' },
  { id: '105', name: 'ガラガラ', nameEn: 'Marowak', soundPath: '/sounds/105.wav', imagePath: '/images/105.png' },
  { id: '106', name: 'サワムラー', nameEn: 'Hitmonlee', soundPath: '/sounds/106.wav', imagePath: '/images/106.png' },
  { id: '107', name: 'エビワラー', nameEn: 'Hitmonchan', soundPath: '/sounds/107.wav', imagePath: '/images/107.png' },
  { id: '108', name: 'ベロリンガ', nameEn: 'Lickitung', soundPath: '/sounds/108.wav', imagePath: '/images/108.png' },
  { id: '109', name: 'ドガース', nameEn: 'Koffing', soundPath: '/sounds/109.wav', imagePath: '/images/109.png' },
  { id: '110', name: 'マタドガス', nameEn: 'Weezing', soundPath: '/sounds/110.wav', imagePath: '/images/110.png' },
  { id: '111', name: 'サイホーン', nameEn: 'Rhyhorn', soundPath: '/sounds/111.wav', imagePath: '/images/111.png' },
  { id: '112', name: 'サイドン', nameEn: 'Rhydon', soundPath: '/sounds/112.wav', imagePath: '/images/112.png' },
  { id: '113', name: 'ラッキー', nameEn: 'Chansey', soundPath: '/sounds/113.wav', imagePath: '/images/113.png' },
  { id: '114', name: 'モンジャラ', nameEn: 'Tangela', soundPath: '/sounds/114.wav', imagePath: '/images/114.png' },
  { id: '115', name: 'ガルーラ', nameEn: 'Kangaskhan', soundPath: '/sounds/115.wav', imagePath: '/images/115.png' },
  { id: '116', name: 'タッツー', nameEn: 'Horsea', soundPath: '/sounds/116.wav', imagePath: '/images/116.png' },
  { id: '117', name: 'シードラ', nameEn: 'Seadra', soundPath: '/sounds/117.wav', imagePath: '/images/117.png' },
  { id: '118', name: 'トサキント', nameEn: 'Goldeen', soundPath: '/sounds/118.wav', imagePath: '/images/118.png' },
  { id: '119', name: 'アズマオウ', nameEn: 'Seaking', soundPath: '/sounds/119.wav', imagePath: '/images/119.png' },
  { id: '120', name: 'ヒトデマン', nameEn: 'Staryu', soundPath: '/sounds/120.wav', imagePath: '/images/120.png' },
  { id: '121', name: 'スターミー', nameEn: 'Starmie', soundPath: '/sounds/121.wav', imagePath: '/images/121.png' },
  { id: '122', name: 'バリヤード', nameEn: 'Mr. Mime', soundPath: '/sounds/122.wav', imagePath: '/images/122.png' },
  { id: '123', name: 'ストライク', nameEn: 'Scyther', soundPath: '/sounds/123.wav', imagePath: '/images/123.png' },
  { id: '124', name: 'ルージュラ', nameEn: 'Jynx', soundPath: '/sounds/124.wav', imagePath: '/images/124.png' },
  { id: '125', name: 'エレブー', nameEn: 'Electabuzz', soundPath: '/sounds/125.wav', imagePath: '/images/125.png' },
  { id: '126', name: 'ブーバー', nameEn: 'Magmar', soundPath: '/sounds/126.wav', imagePath: '/images/126.png' },
  { id: '127', name: 'カイロス', nameEn: 'Pinsir', soundPath: '/sounds/127.wav', imagePath: '/images/127.png' },
  { id: '128', name: 'ケンタロス', nameEn: 'Tauros', soundPath: '/sounds/128.wav', imagePath: '/images/128.png' },
  { id: '129', name: 'コイキング', nameEn: 'Magikarp', soundPath: '/sounds/129.wav', imagePath: '/images/129.png' },
  { id: '130', name: 'ギャラドス', nameEn: 'Gyarados', soundPath: '/sounds/130.wav', imagePath: '/images/130.png' },
  { id: '131', name: 'ラプラス', nameEn: 'Lapras', soundPath: '/sounds/131.wav', imagePath: '/images/131.png' },
  { id: '132', name: 'メタモン', nameEn: 'Ditto', soundPath: '/sounds/132.wav', imagePath: '/images/132.png' },
  { id: '133', name: 'イーブイ', nameEn: 'Eevee', soundPath: '/sounds/133.wav', imagePath: '/images/133.png' },
  { id: '134', name: 'シャワーズ', nameEn: 'Vaporeon', soundPath: '/sounds/134.wav', imagePath: '/images/134.png' },
  { id: '135', name: 'サンダース', nameEn: 'Jolteon', soundPath: '/sounds/135.wav', imagePath: '/images/135.png' },
  { id: '136', name: 'ブースター', nameEn: 'Flareon', soundPath: '/sounds/136.wav', imagePath: '/images/136.png' },
  { id: '137', name: 'ポリゴン', nameEn: 'Porygon', soundPath: '/sounds/137.wav', imagePath: '/images/137.png' },
  { id: '138', name: 'オムナイト', nameEn: 'Omanyte', soundPath: '/sounds/138.wav', imagePath: '/images/138.png' },
  { id: '139', name: 'オムスター', nameEn: 'Omastar', soundPath: '/sounds/139.wav', imagePath: '/images/139.png' },
  { id: '140', name: 'カブト', nameEn: 'Kabuto', soundPath: '/sounds/140.wav', imagePath: '/images/140.png' },
  { id: '141', name: 'カブトプス', nameEn: 'Kabutops', soundPath: '/sounds/141.wav', imagePath: '/images/141.png' },
  { id: '142', name: 'プテラ', nameEn: 'Aerodactyl', soundPath: '/sounds/142.wav', imagePath: '/images/142.png' },
  { id: '143', name: 'カビゴン', nameEn: 'Snorlax', soundPath: '/sounds/143.wav', imagePath: '/images/143.png' },
  { id: '144', name: 'フリーザー', nameEn: 'Articuno', soundPath: '/sounds/144.wav', imagePath: '/images/144.png' },
  { id: '145', name: 'サンダー', nameEn: 'Zapdos', soundPath: '/sounds/145.wav', imagePath: '/images/145.png' },
  { id: '146', name: 'ファイヤー', nameEn: 'Moltres', soundPath: '/sounds/146.wav', imagePath: '/images/146.png' },
  { id: '147', name: 'ミニリュウ', nameEn: 'Dratini', soundPath: '/sounds/147.wav', imagePath: '/images/147.png' },
  { id: '148', name: 'ハクリュー', nameEn: 'Dragonair', soundPath: '/sounds/148.wav', imagePath: '/images/148.png' },
  { id: '149', name: 'カイリュー', nameEn: 'Dragonite', soundPath: '/sounds/149.wav', imagePath: '/images/149.png' },
  { id: '150', name: 'ミュウツー', nameEn: 'Mewtwo', soundPath: '/sounds/150.wav', imagePath: '/images/150.png' },
  { id: '151', name: 'ミュウ', nameEn: 'Mew', soundPath: '/sounds/151.wav', imagePath: '/images/151.png' },
];

export function getRandomPokemon(): Pokemon {
  return POKEMON_LIST[Math.floor(Math.random() * POKEMON_LIST.length)];
}

export function getRandomPokemons(count: number, excludeId?: string): Pokemon[] {
  const available = POKEMON_LIST.filter(p => p.id !== excludeId);
  const shuffled = shuffleArray(available);
  return shuffled.slice(0, count);
}

export function getPokemonById(id: string): Pokemon | undefined {
  return POKEMON_LIST.find(p => p.id === id);
}

export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

