export interface Pokemon {
  id: string;
  name: string;
  nameEn: string;
  soundPath: string;
  imagePath: string;
  generation: 1 | 2 | 3 | 4 | 5;
}

export interface GenerationInfo {
  id: 1 | 2 | 3 | 4 | 5;
  name: string;
  nameEn: string;
  region: string;
  regionEn: string;
  games: string;
  gamesEn: string;
  color: string;
  bgColor: string;
  range: [number, number];
}

export const GENERATIONS: GenerationInfo[] = [
  { id: 1, name: '第1世代', nameEn: 'Gen I', region: 'カントー', regionEn: 'Kanto', games: '赤/緑/青/ピカチュウ', gamesEn: 'Red/Green/Blue/Yellow', color: 'text-red-600', bgColor: 'bg-red-50 border-red-200', range: [1, 151] },
  { id: 2, name: '第2世代', nameEn: 'Gen II', region: 'ジョウト', regionEn: 'Johto', games: '金/銀/クリスタル', gamesEn: 'Gold/Silver/Crystal', color: 'text-yellow-600', bgColor: 'bg-yellow-50 border-yellow-200', range: [152, 251] },
  { id: 3, name: '第3世代', nameEn: 'Gen III', region: 'ホウエン', regionEn: 'Hoenn', games: 'ルビー/サファイア/エメラルド', gamesEn: 'Ruby/Sapphire/Emerald', color: 'text-green-600', bgColor: 'bg-green-50 border-green-200', range: [252, 386] },
  { id: 4, name: '第4世代', nameEn: 'Gen IV', region: 'シンオウ', regionEn: 'Sinnoh', games: 'ダイヤモンド/パール/プラチナ', gamesEn: 'Diamond/Pearl/Platinum', color: 'text-blue-600', bgColor: 'bg-blue-50 border-blue-200', range: [387, 493] },
  { id: 5, name: '第5世代', nameEn: 'Gen V', region: 'イッシュ', regionEn: 'Unova', games: 'ブラック/ホワイト', gamesEn: 'Black/White', color: 'text-purple-600', bgColor: 'bg-purple-50 border-purple-200', range: [494, 649] },
];

function soundPath(id: string): string {
  const num = parseInt(id, 10);
  return num <= 386 ? `/sounds/${id}.wav` : `/sounds/${id}.mp3`;
}

function imagePath(id: string): string {
  return `/poke_pic/${id}.png`;
}

export const POKEMON_LIST: Pokemon[] = [
  // === 第1世代 (001-151) ===
  { id: '001', name: 'フシギダネ', nameEn: 'Bulbasaur', soundPath: soundPath('001'), imagePath: imagePath('001'), generation: 1 },
  { id: '002', name: 'フシギソウ', nameEn: 'Ivysaur', soundPath: soundPath('002'), imagePath: imagePath('002'), generation: 1 },
  { id: '003', name: 'フシギバナ', nameEn: 'Venusaur', soundPath: soundPath('003'), imagePath: imagePath('003'), generation: 1 },
  { id: '004', name: 'ヒトカゲ', nameEn: 'Charmander', soundPath: soundPath('004'), imagePath: imagePath('004'), generation: 1 },
  { id: '005', name: 'リザード', nameEn: 'Charmeleon', soundPath: soundPath('005'), imagePath: imagePath('005'), generation: 1 },
  { id: '006', name: 'リザードン', nameEn: 'Charizard', soundPath: soundPath('006'), imagePath: imagePath('006'), generation: 1 },
  { id: '007', name: 'ゼニガメ', nameEn: 'Squirtle', soundPath: soundPath('007'), imagePath: imagePath('007'), generation: 1 },
  { id: '008', name: 'カメール', nameEn: 'Wartortle', soundPath: soundPath('008'), imagePath: imagePath('008'), generation: 1 },
  { id: '009', name: 'カメックス', nameEn: 'Blastoise', soundPath: soundPath('009'), imagePath: imagePath('009'), generation: 1 },
  { id: '010', name: 'キャタピー', nameEn: 'Caterpie', soundPath: soundPath('010'), imagePath: imagePath('010'), generation: 1 },
  { id: '011', name: 'トランセル', nameEn: 'Metapod', soundPath: soundPath('011'), imagePath: imagePath('011'), generation: 1 },
  { id: '012', name: 'バタフリー', nameEn: 'Butterfree', soundPath: soundPath('012'), imagePath: imagePath('012'), generation: 1 },
  { id: '013', name: 'ビードル', nameEn: 'Weedle', soundPath: soundPath('013'), imagePath: imagePath('013'), generation: 1 },
  { id: '014', name: 'コクーン', nameEn: 'Kakuna', soundPath: soundPath('014'), imagePath: imagePath('014'), generation: 1 },
  { id: '015', name: 'スピアー', nameEn: 'Beedrill', soundPath: soundPath('015'), imagePath: imagePath('015'), generation: 1 },
  { id: '016', name: 'ポッポ', nameEn: 'Pidgey', soundPath: soundPath('016'), imagePath: imagePath('016'), generation: 1 },
  { id: '017', name: 'ピジョン', nameEn: 'Pidgeotto', soundPath: soundPath('017'), imagePath: imagePath('017'), generation: 1 },
  { id: '018', name: 'ピジョット', nameEn: 'Pidgeot', soundPath: soundPath('018'), imagePath: imagePath('018'), generation: 1 },
  { id: '019', name: 'コラッタ', nameEn: 'Rattata', soundPath: soundPath('019'), imagePath: imagePath('019'), generation: 1 },
  { id: '020', name: 'ラッタ', nameEn: 'Raticate', soundPath: soundPath('020'), imagePath: imagePath('020'), generation: 1 },
  { id: '021', name: 'オニスズメ', nameEn: 'Spearow', soundPath: soundPath('021'), imagePath: imagePath('021'), generation: 1 },
  { id: '022', name: 'オニドリル', nameEn: 'Fearow', soundPath: soundPath('022'), imagePath: imagePath('022'), generation: 1 },
  { id: '023', name: 'アーボ', nameEn: 'Ekans', soundPath: soundPath('023'), imagePath: imagePath('023'), generation: 1 },
  { id: '024', name: 'アーボック', nameEn: 'Arbok', soundPath: soundPath('024'), imagePath: imagePath('024'), generation: 1 },
  { id: '025', name: 'ピカチュウ', nameEn: 'Pikachu', soundPath: soundPath('025'), imagePath: imagePath('025'), generation: 1 },
  { id: '026', name: 'ライチュウ', nameEn: 'Raichu', soundPath: soundPath('026'), imagePath: imagePath('026'), generation: 1 },
  { id: '027', name: 'サンド', nameEn: 'Sandshrew', soundPath: soundPath('027'), imagePath: imagePath('027'), generation: 1 },
  { id: '028', name: 'サンドパン', nameEn: 'Sandslash', soundPath: soundPath('028'), imagePath: imagePath('028'), generation: 1 },
  { id: '029', name: 'ニドラン♀', nameEn: 'Nidoran♀', soundPath: soundPath('029'), imagePath: imagePath('029'), generation: 1 },
  { id: '030', name: 'ニドリーナ', nameEn: 'Nidorina', soundPath: soundPath('030'), imagePath: imagePath('030'), generation: 1 },
  { id: '031', name: 'ニドクイン', nameEn: 'Nidoqueen', soundPath: soundPath('031'), imagePath: imagePath('031'), generation: 1 },
  { id: '032', name: 'ニドラン♂', nameEn: 'Nidoran♂', soundPath: soundPath('032'), imagePath: imagePath('032'), generation: 1 },
  { id: '033', name: 'ニドリーノ', nameEn: 'Nidorino', soundPath: soundPath('033'), imagePath: imagePath('033'), generation: 1 },
  { id: '034', name: 'ニドキング', nameEn: 'Nidoking', soundPath: soundPath('034'), imagePath: imagePath('034'), generation: 1 },
  { id: '035', name: 'ピッピ', nameEn: 'Clefairy', soundPath: soundPath('035'), imagePath: imagePath('035'), generation: 1 },
  { id: '036', name: 'ピクシー', nameEn: 'Clefable', soundPath: soundPath('036'), imagePath: imagePath('036'), generation: 1 },
  { id: '037', name: 'ロコン', nameEn: 'Vulpix', soundPath: soundPath('037'), imagePath: imagePath('037'), generation: 1 },
  { id: '038', name: 'キュウコン', nameEn: 'Ninetales', soundPath: soundPath('038'), imagePath: imagePath('038'), generation: 1 },
  { id: '039', name: 'プリン', nameEn: 'Jigglypuff', soundPath: soundPath('039'), imagePath: imagePath('039'), generation: 1 },
  { id: '040', name: 'プクリン', nameEn: 'Wigglytuff', soundPath: soundPath('040'), imagePath: imagePath('040'), generation: 1 },
  { id: '041', name: 'ズバット', nameEn: 'Zubat', soundPath: soundPath('041'), imagePath: imagePath('041'), generation: 1 },
  { id: '042', name: 'ゴルバット', nameEn: 'Golbat', soundPath: soundPath('042'), imagePath: imagePath('042'), generation: 1 },
  { id: '043', name: 'ナゾノクサ', nameEn: 'Oddish', soundPath: soundPath('043'), imagePath: imagePath('043'), generation: 1 },
  { id: '044', name: 'クサイハナ', nameEn: 'Gloom', soundPath: soundPath('044'), imagePath: imagePath('044'), generation: 1 },
  { id: '045', name: 'ラフレシア', nameEn: 'Vileplume', soundPath: soundPath('045'), imagePath: imagePath('045'), generation: 1 },
  { id: '046', name: 'パラス', nameEn: 'Paras', soundPath: soundPath('046'), imagePath: imagePath('046'), generation: 1 },
  { id: '047', name: 'パラセクト', nameEn: 'Parasect', soundPath: soundPath('047'), imagePath: imagePath('047'), generation: 1 },
  { id: '048', name: 'コンパン', nameEn: 'Venonat', soundPath: soundPath('048'), imagePath: imagePath('048'), generation: 1 },
  { id: '049', name: 'モルフォン', nameEn: 'Venomoth', soundPath: soundPath('049'), imagePath: imagePath('049'), generation: 1 },
  { id: '050', name: 'ディグダ', nameEn: 'Diglett', soundPath: soundPath('050'), imagePath: imagePath('050'), generation: 1 },
  { id: '051', name: 'ダグトリオ', nameEn: 'Dugtrio', soundPath: soundPath('051'), imagePath: imagePath('051'), generation: 1 },
  { id: '052', name: 'ニャース', nameEn: 'Meowth', soundPath: soundPath('052'), imagePath: imagePath('052'), generation: 1 },
  { id: '053', name: 'ペルシアン', nameEn: 'Persian', soundPath: soundPath('053'), imagePath: imagePath('053'), generation: 1 },
  { id: '054', name: 'コダック', nameEn: 'Psyduck', soundPath: soundPath('054'), imagePath: imagePath('054'), generation: 1 },
  { id: '055', name: 'ゴルダック', nameEn: 'Golduck', soundPath: soundPath('055'), imagePath: imagePath('055'), generation: 1 },
  { id: '056', name: 'マンキー', nameEn: 'Mankey', soundPath: soundPath('056'), imagePath: imagePath('056'), generation: 1 },
  { id: '057', name: 'オコリザル', nameEn: 'Primeape', soundPath: soundPath('057'), imagePath: imagePath('057'), generation: 1 },
  { id: '058', name: 'ガーディ', nameEn: 'Growlithe', soundPath: soundPath('058'), imagePath: imagePath('058'), generation: 1 },
  { id: '059', name: 'ウインディ', nameEn: 'Arcanine', soundPath: soundPath('059'), imagePath: imagePath('059'), generation: 1 },
  { id: '060', name: 'ニョロモ', nameEn: 'Poliwag', soundPath: soundPath('060'), imagePath: imagePath('060'), generation: 1 },
  { id: '061', name: 'ニョロゾ', nameEn: 'Poliwhirl', soundPath: soundPath('061'), imagePath: imagePath('061'), generation: 1 },
  { id: '062', name: 'ニョロボン', nameEn: 'Poliwrath', soundPath: soundPath('062'), imagePath: imagePath('062'), generation: 1 },
  { id: '063', name: 'ケーシィ', nameEn: 'Abra', soundPath: soundPath('063'), imagePath: imagePath('063'), generation: 1 },
  { id: '064', name: 'ユンゲラー', nameEn: 'Kadabra', soundPath: soundPath('064'), imagePath: imagePath('064'), generation: 1 },
  { id: '065', name: 'フーディン', nameEn: 'Alakazam', soundPath: soundPath('065'), imagePath: imagePath('065'), generation: 1 },
  { id: '066', name: 'ワンリキー', nameEn: 'Machop', soundPath: soundPath('066'), imagePath: imagePath('066'), generation: 1 },
  { id: '067', name: 'ゴーリキー', nameEn: 'Machoke', soundPath: soundPath('067'), imagePath: imagePath('067'), generation: 1 },
  { id: '068', name: 'カイリキー', nameEn: 'Machamp', soundPath: soundPath('068'), imagePath: imagePath('068'), generation: 1 },
  { id: '069', name: 'マダツボミ', nameEn: 'Bellsprout', soundPath: soundPath('069'), imagePath: imagePath('069'), generation: 1 },
  { id: '070', name: 'ウツドン', nameEn: 'Weepinbell', soundPath: soundPath('070'), imagePath: imagePath('070'), generation: 1 },
  { id: '071', name: 'ウツボット', nameEn: 'Victreebel', soundPath: soundPath('071'), imagePath: imagePath('071'), generation: 1 },
  { id: '072', name: 'メノクラゲ', nameEn: 'Tentacool', soundPath: soundPath('072'), imagePath: imagePath('072'), generation: 1 },
  { id: '073', name: 'ドククラゲ', nameEn: 'Tentacruel', soundPath: soundPath('073'), imagePath: imagePath('073'), generation: 1 },
  { id: '074', name: 'イシツブテ', nameEn: 'Geodude', soundPath: soundPath('074'), imagePath: imagePath('074'), generation: 1 },
  { id: '075', name: 'ゴローン', nameEn: 'Graveler', soundPath: soundPath('075'), imagePath: imagePath('075'), generation: 1 },
  { id: '076', name: 'ゴローニャ', nameEn: 'Golem', soundPath: soundPath('076'), imagePath: imagePath('076'), generation: 1 },
  { id: '077', name: 'ポニータ', nameEn: 'Ponyta', soundPath: soundPath('077'), imagePath: imagePath('077'), generation: 1 },
  { id: '078', name: 'ギャロップ', nameEn: 'Rapidash', soundPath: soundPath('078'), imagePath: imagePath('078'), generation: 1 },
  { id: '079', name: 'ヤドン', nameEn: 'Slowpoke', soundPath: soundPath('079'), imagePath: imagePath('079'), generation: 1 },
  { id: '080', name: 'ヤドラン', nameEn: 'Slowbro', soundPath: soundPath('080'), imagePath: imagePath('080'), generation: 1 },
  { id: '081', name: 'コイル', nameEn: 'Magnemite', soundPath: soundPath('081'), imagePath: imagePath('081'), generation: 1 },
  { id: '082', name: 'レアコイル', nameEn: 'Magneton', soundPath: soundPath('082'), imagePath: imagePath('082'), generation: 1 },
  { id: '083', name: 'カモネギ', nameEn: "Farfetch'd", soundPath: soundPath('083'), imagePath: imagePath('083'), generation: 1 },
  { id: '084', name: 'ドードー', nameEn: 'Doduo', soundPath: soundPath('084'), imagePath: imagePath('084'), generation: 1 },
  { id: '085', name: 'ドードリオ', nameEn: 'Dodrio', soundPath: soundPath('085'), imagePath: imagePath('085'), generation: 1 },
  { id: '086', name: 'パウワウ', nameEn: 'Seel', soundPath: soundPath('086'), imagePath: imagePath('086'), generation: 1 },
  { id: '087', name: 'ジュゴン', nameEn: 'Dewgong', soundPath: soundPath('087'), imagePath: imagePath('087'), generation: 1 },
  { id: '088', name: 'ベトベター', nameEn: 'Grimer', soundPath: soundPath('088'), imagePath: imagePath('088'), generation: 1 },
  { id: '089', name: 'ベトベトン', nameEn: 'Muk', soundPath: soundPath('089'), imagePath: imagePath('089'), generation: 1 },
  { id: '090', name: 'シェルダー', nameEn: 'Shellder', soundPath: soundPath('090'), imagePath: imagePath('090'), generation: 1 },
  { id: '091', name: 'パルシェン', nameEn: 'Cloyster', soundPath: soundPath('091'), imagePath: imagePath('091'), generation: 1 },
  { id: '092', name: 'ゴース', nameEn: 'Gastly', soundPath: soundPath('092'), imagePath: imagePath('092'), generation: 1 },
  { id: '093', name: 'ゴースト', nameEn: 'Haunter', soundPath: soundPath('093'), imagePath: imagePath('093'), generation: 1 },
  { id: '094', name: 'ゲンガー', nameEn: 'Gengar', soundPath: soundPath('094'), imagePath: imagePath('094'), generation: 1 },
  { id: '095', name: 'イワーク', nameEn: 'Onix', soundPath: soundPath('095'), imagePath: imagePath('095'), generation: 1 },
  { id: '096', name: 'スリープ', nameEn: 'Drowzee', soundPath: soundPath('096'), imagePath: imagePath('096'), generation: 1 },
  { id: '097', name: 'スリーパー', nameEn: 'Hypno', soundPath: soundPath('097'), imagePath: imagePath('097'), generation: 1 },
  { id: '098', name: 'クラブ', nameEn: 'Krabby', soundPath: soundPath('098'), imagePath: imagePath('098'), generation: 1 },
  { id: '099', name: 'キングラー', nameEn: 'Kingler', soundPath: soundPath('099'), imagePath: imagePath('099'), generation: 1 },
  { id: '100', name: 'ビリリダマ', nameEn: 'Voltorb', soundPath: soundPath('100'), imagePath: imagePath('100'), generation: 1 },
  { id: '101', name: 'マルマイン', nameEn: 'Electrode', soundPath: soundPath('101'), imagePath: imagePath('101'), generation: 1 },
  { id: '102', name: 'タマタマ', nameEn: 'Exeggcute', soundPath: soundPath('102'), imagePath: imagePath('102'), generation: 1 },
  { id: '103', name: 'ナッシー', nameEn: 'Exeggutor', soundPath: soundPath('103'), imagePath: imagePath('103'), generation: 1 },
  { id: '104', name: 'カラカラ', nameEn: 'Cubone', soundPath: soundPath('104'), imagePath: imagePath('104'), generation: 1 },
  { id: '105', name: 'ガラガラ', nameEn: 'Marowak', soundPath: soundPath('105'), imagePath: imagePath('105'), generation: 1 },
  { id: '106', name: 'サワムラー', nameEn: 'Hitmonlee', soundPath: soundPath('106'), imagePath: imagePath('106'), generation: 1 },
  { id: '107', name: 'エビワラー', nameEn: 'Hitmonchan', soundPath: soundPath('107'), imagePath: imagePath('107'), generation: 1 },
  { id: '108', name: 'ベロリンガ', nameEn: 'Lickitung', soundPath: soundPath('108'), imagePath: imagePath('108'), generation: 1 },
  { id: '109', name: 'ドガース', nameEn: 'Koffing', soundPath: soundPath('109'), imagePath: imagePath('109'), generation: 1 },
  { id: '110', name: 'マタドガス', nameEn: 'Weezing', soundPath: soundPath('110'), imagePath: imagePath('110'), generation: 1 },
  { id: '111', name: 'サイホーン', nameEn: 'Rhyhorn', soundPath: soundPath('111'), imagePath: imagePath('111'), generation: 1 },
  { id: '112', name: 'サイドン', nameEn: 'Rhydon', soundPath: soundPath('112'), imagePath: imagePath('112'), generation: 1 },
  { id: '113', name: 'ラッキー', nameEn: 'Chansey', soundPath: soundPath('113'), imagePath: imagePath('113'), generation: 1 },
  { id: '114', name: 'モンジャラ', nameEn: 'Tangela', soundPath: soundPath('114'), imagePath: imagePath('114'), generation: 1 },
  { id: '115', name: 'ガルーラ', nameEn: 'Kangaskhan', soundPath: soundPath('115'), imagePath: imagePath('115'), generation: 1 },
  { id: '116', name: 'タッツー', nameEn: 'Horsea', soundPath: soundPath('116'), imagePath: imagePath('116'), generation: 1 },
  { id: '117', name: 'シードラ', nameEn: 'Seadra', soundPath: soundPath('117'), imagePath: imagePath('117'), generation: 1 },
  { id: '118', name: 'トサキント', nameEn: 'Goldeen', soundPath: soundPath('118'), imagePath: imagePath('118'), generation: 1 },
  { id: '119', name: 'アズマオウ', nameEn: 'Seaking', soundPath: soundPath('119'), imagePath: imagePath('119'), generation: 1 },
  { id: '120', name: 'ヒトデマン', nameEn: 'Staryu', soundPath: soundPath('120'), imagePath: imagePath('120'), generation: 1 },
  { id: '121', name: 'スターミー', nameEn: 'Starmie', soundPath: soundPath('121'), imagePath: imagePath('121'), generation: 1 },
  { id: '122', name: 'バリヤード', nameEn: 'Mr. Mime', soundPath: soundPath('122'), imagePath: imagePath('122'), generation: 1 },
  { id: '123', name: 'ストライク', nameEn: 'Scyther', soundPath: soundPath('123'), imagePath: imagePath('123'), generation: 1 },
  { id: '124', name: 'ルージュラ', nameEn: 'Jynx', soundPath: soundPath('124'), imagePath: imagePath('124'), generation: 1 },
  { id: '125', name: 'エレブー', nameEn: 'Electabuzz', soundPath: soundPath('125'), imagePath: imagePath('125'), generation: 1 },
  { id: '126', name: 'ブーバー', nameEn: 'Magmar', soundPath: soundPath('126'), imagePath: imagePath('126'), generation: 1 },
  { id: '127', name: 'カイロス', nameEn: 'Pinsir', soundPath: soundPath('127'), imagePath: imagePath('127'), generation: 1 },
  { id: '128', name: 'ケンタロス', nameEn: 'Tauros', soundPath: soundPath('128'), imagePath: imagePath('128'), generation: 1 },
  { id: '129', name: 'コイキング', nameEn: 'Magikarp', soundPath: soundPath('129'), imagePath: imagePath('129'), generation: 1 },
  { id: '130', name: 'ギャラドス', nameEn: 'Gyarados', soundPath: soundPath('130'), imagePath: imagePath('130'), generation: 1 },
  { id: '131', name: 'ラプラス', nameEn: 'Lapras', soundPath: soundPath('131'), imagePath: imagePath('131'), generation: 1 },
  { id: '132', name: 'メタモン', nameEn: 'Ditto', soundPath: soundPath('132'), imagePath: imagePath('132'), generation: 1 },
  { id: '133', name: 'イーブイ', nameEn: 'Eevee', soundPath: soundPath('133'), imagePath: imagePath('133'), generation: 1 },
  { id: '134', name: 'シャワーズ', nameEn: 'Vaporeon', soundPath: soundPath('134'), imagePath: imagePath('134'), generation: 1 },
  { id: '135', name: 'サンダース', nameEn: 'Jolteon', soundPath: soundPath('135'), imagePath: imagePath('135'), generation: 1 },
  { id: '136', name: 'ブースター', nameEn: 'Flareon', soundPath: soundPath('136'), imagePath: imagePath('136'), generation: 1 },
  { id: '137', name: 'ポリゴン', nameEn: 'Porygon', soundPath: soundPath('137'), imagePath: imagePath('137'), generation: 1 },
  { id: '138', name: 'オムナイト', nameEn: 'Omanyte', soundPath: soundPath('138'), imagePath: imagePath('138'), generation: 1 },
  { id: '139', name: 'オムスター', nameEn: 'Omastar', soundPath: soundPath('139'), imagePath: imagePath('139'), generation: 1 },
  { id: '140', name: 'カブト', nameEn: 'Kabuto', soundPath: soundPath('140'), imagePath: imagePath('140'), generation: 1 },
  { id: '141', name: 'カブトプス', nameEn: 'Kabutops', soundPath: soundPath('141'), imagePath: imagePath('141'), generation: 1 },
  { id: '142', name: 'プテラ', nameEn: 'Aerodactyl', soundPath: soundPath('142'), imagePath: imagePath('142'), generation: 1 },
  { id: '143', name: 'カビゴン', nameEn: 'Snorlax', soundPath: soundPath('143'), imagePath: imagePath('143'), generation: 1 },
  { id: '144', name: 'フリーザー', nameEn: 'Articuno', soundPath: soundPath('144'), imagePath: imagePath('144'), generation: 1 },
  { id: '145', name: 'サンダー', nameEn: 'Zapdos', soundPath: soundPath('145'), imagePath: imagePath('145'), generation: 1 },
  { id: '146', name: 'ファイヤー', nameEn: 'Moltres', soundPath: soundPath('146'), imagePath: imagePath('146'), generation: 1 },
  { id: '147', name: 'ミニリュウ', nameEn: 'Dratini', soundPath: soundPath('147'), imagePath: imagePath('147'), generation: 1 },
  { id: '148', name: 'ハクリュー', nameEn: 'Dragonair', soundPath: soundPath('148'), imagePath: imagePath('148'), generation: 1 },
  { id: '149', name: 'カイリュー', nameEn: 'Dragonite', soundPath: soundPath('149'), imagePath: imagePath('149'), generation: 1 },
  { id: '150', name: 'ミュウツー', nameEn: 'Mewtwo', soundPath: soundPath('150'), imagePath: imagePath('150'), generation: 1 },
  { id: '151', name: 'ミュウ', nameEn: 'Mew', soundPath: soundPath('151'), imagePath: imagePath('151'), generation: 1 },

  // === 第2世代 (152-251) ===
  { id: '152', name: 'チコリータ', nameEn: 'Chikorita', soundPath: soundPath('152'), imagePath: imagePath('152'), generation: 2 },
  { id: '153', name: 'ベイリーフ', nameEn: 'Bayleef', soundPath: soundPath('153'), imagePath: imagePath('153'), generation: 2 },
  { id: '154', name: 'メガニウム', nameEn: 'Meganium', soundPath: soundPath('154'), imagePath: imagePath('154'), generation: 2 },
  { id: '155', name: 'ヒノアラシ', nameEn: 'Cyndaquil', soundPath: soundPath('155'), imagePath: imagePath('155'), generation: 2 },
  { id: '156', name: 'マグマラシ', nameEn: 'Quilava', soundPath: soundPath('156'), imagePath: imagePath('156'), generation: 2 },
  { id: '157', name: 'バクフーン', nameEn: 'Typhlosion', soundPath: soundPath('157'), imagePath: imagePath('157'), generation: 2 },
  { id: '158', name: 'ワニノコ', nameEn: 'Totodile', soundPath: soundPath('158'), imagePath: imagePath('158'), generation: 2 },
  { id: '159', name: 'アリゲイツ', nameEn: 'Croconaw', soundPath: soundPath('159'), imagePath: imagePath('159'), generation: 2 },
  { id: '160', name: 'オーダイル', nameEn: 'Feraligatr', soundPath: soundPath('160'), imagePath: imagePath('160'), generation: 2 },
  { id: '161', name: 'オタチ', nameEn: 'Sentret', soundPath: soundPath('161'), imagePath: imagePath('161'), generation: 2 },
  { id: '162', name: 'オオタチ', nameEn: 'Furret', soundPath: soundPath('162'), imagePath: imagePath('162'), generation: 2 },
  { id: '163', name: 'ホーホー', nameEn: 'Hoothoot', soundPath: soundPath('163'), imagePath: imagePath('163'), generation: 2 },
  { id: '164', name: 'ヨルノズク', nameEn: 'Noctowl', soundPath: soundPath('164'), imagePath: imagePath('164'), generation: 2 },
  { id: '165', name: 'レディバ', nameEn: 'Ledyba', soundPath: soundPath('165'), imagePath: imagePath('165'), generation: 2 },
  { id: '166', name: 'レディアン', nameEn: 'Ledian', soundPath: soundPath('166'), imagePath: imagePath('166'), generation: 2 },
  { id: '167', name: 'イトマル', nameEn: 'Spinarak', soundPath: soundPath('167'), imagePath: imagePath('167'), generation: 2 },
  { id: '168', name: 'アリアドス', nameEn: 'Ariados', soundPath: soundPath('168'), imagePath: imagePath('168'), generation: 2 },
  { id: '169', name: 'クロバット', nameEn: 'Crobat', soundPath: soundPath('169'), imagePath: imagePath('169'), generation: 2 },
  { id: '170', name: 'チョンチー', nameEn: 'Chinchou', soundPath: soundPath('170'), imagePath: imagePath('170'), generation: 2 },
  { id: '171', name: 'ランターン', nameEn: 'Lanturn', soundPath: soundPath('171'), imagePath: imagePath('171'), generation: 2 },
  { id: '172', name: 'ピチュー', nameEn: 'Pichu', soundPath: soundPath('172'), imagePath: imagePath('172'), generation: 2 },
  { id: '173', name: 'ピィ', nameEn: 'Cleffa', soundPath: soundPath('173'), imagePath: imagePath('173'), generation: 2 },
  { id: '174', name: 'ププリン', nameEn: 'Igglybuff', soundPath: soundPath('174'), imagePath: imagePath('174'), generation: 2 },
  { id: '175', name: 'トゲピー', nameEn: 'Togepi', soundPath: soundPath('175'), imagePath: imagePath('175'), generation: 2 },
  { id: '176', name: 'トゲチック', nameEn: 'Togetic', soundPath: soundPath('176'), imagePath: imagePath('176'), generation: 2 },
  { id: '177', name: 'ネイティ', nameEn: 'Natu', soundPath: soundPath('177'), imagePath: imagePath('177'), generation: 2 },
  { id: '178', name: 'ネイティオ', nameEn: 'Xatu', soundPath: soundPath('178'), imagePath: imagePath('178'), generation: 2 },
  { id: '179', name: 'メリープ', nameEn: 'Mareep', soundPath: soundPath('179'), imagePath: imagePath('179'), generation: 2 },
  { id: '180', name: 'モココ', nameEn: 'Flaaffy', soundPath: soundPath('180'), imagePath: imagePath('180'), generation: 2 },
  { id: '181', name: 'デンリュウ', nameEn: 'Ampharos', soundPath: soundPath('181'), imagePath: imagePath('181'), generation: 2 },
  { id: '182', name: 'キレイハナ', nameEn: 'Bellossom', soundPath: soundPath('182'), imagePath: imagePath('182'), generation: 2 },
  { id: '183', name: 'マリル', nameEn: 'Marill', soundPath: soundPath('183'), imagePath: imagePath('183'), generation: 2 },
  { id: '184', name: 'マリルリ', nameEn: 'Azumarill', soundPath: soundPath('184'), imagePath: imagePath('184'), generation: 2 },
  { id: '185', name: 'ウソッキー', nameEn: 'Sudowoodo', soundPath: soundPath('185'), imagePath: imagePath('185'), generation: 2 },
  { id: '186', name: 'ニョロトノ', nameEn: 'Politoed', soundPath: soundPath('186'), imagePath: imagePath('186'), generation: 2 },
  { id: '187', name: 'ハネッコ', nameEn: 'Hoppip', soundPath: soundPath('187'), imagePath: imagePath('187'), generation: 2 },
  { id: '188', name: 'ポポッコ', nameEn: 'Skiploom', soundPath: soundPath('188'), imagePath: imagePath('188'), generation: 2 },
  { id: '189', name: 'ワタッコ', nameEn: 'Jumpluff', soundPath: soundPath('189'), imagePath: imagePath('189'), generation: 2 },
  { id: '190', name: 'エイパム', nameEn: 'Aipom', soundPath: soundPath('190'), imagePath: imagePath('190'), generation: 2 },
  { id: '191', name: 'ヒマナッツ', nameEn: 'Sunkern', soundPath: soundPath('191'), imagePath: imagePath('191'), generation: 2 },
  { id: '192', name: 'キマワリ', nameEn: 'Sunflora', soundPath: soundPath('192'), imagePath: imagePath('192'), generation: 2 },
  { id: '193', name: 'ヤンヤンマ', nameEn: 'Yanma', soundPath: soundPath('193'), imagePath: imagePath('193'), generation: 2 },
  { id: '194', name: 'ウパー', nameEn: 'Wooper', soundPath: soundPath('194'), imagePath: imagePath('194'), generation: 2 },
  { id: '195', name: 'ヌオー', nameEn: 'Quagsire', soundPath: soundPath('195'), imagePath: imagePath('195'), generation: 2 },
  { id: '196', name: 'エーフィ', nameEn: 'Espeon', soundPath: soundPath('196'), imagePath: imagePath('196'), generation: 2 },
  { id: '197', name: 'ブラッキー', nameEn: 'Umbreon', soundPath: soundPath('197'), imagePath: imagePath('197'), generation: 2 },
  { id: '198', name: 'ヤミカラス', nameEn: 'Murkrow', soundPath: soundPath('198'), imagePath: imagePath('198'), generation: 2 },
  { id: '199', name: 'ヤドキング', nameEn: 'Slowking', soundPath: soundPath('199'), imagePath: imagePath('199'), generation: 2 },
  { id: '200', name: 'ムウマ', nameEn: 'Misdreavus', soundPath: soundPath('200'), imagePath: imagePath('200'), generation: 2 },
  { id: '201', name: 'アンノーン', nameEn: 'Unown', soundPath: soundPath('201'), imagePath: imagePath('201'), generation: 2 },
  { id: '202', name: 'ソーナンス', nameEn: 'Wobbuffet', soundPath: soundPath('202'), imagePath: imagePath('202'), generation: 2 },
  { id: '203', name: 'キリンリキ', nameEn: 'Girafarig', soundPath: soundPath('203'), imagePath: imagePath('203'), generation: 2 },
  { id: '204', name: 'クヌギダマ', nameEn: 'Pineco', soundPath: soundPath('204'), imagePath: imagePath('204'), generation: 2 },
  { id: '205', name: 'フォレトス', nameEn: 'Forretress', soundPath: soundPath('205'), imagePath: imagePath('205'), generation: 2 },
  { id: '206', name: 'ノコッチ', nameEn: 'Dunsparce', soundPath: soundPath('206'), imagePath: imagePath('206'), generation: 2 },
  { id: '207', name: 'グライガー', nameEn: 'Gligar', soundPath: soundPath('207'), imagePath: imagePath('207'), generation: 2 },
  { id: '208', name: 'ハガネール', nameEn: 'Steelix', soundPath: soundPath('208'), imagePath: imagePath('208'), generation: 2 },
  { id: '209', name: 'ブルー', nameEn: 'Snubbull', soundPath: soundPath('209'), imagePath: imagePath('209'), generation: 2 },
  { id: '210', name: 'グランブル', nameEn: 'Granbull', soundPath: soundPath('210'), imagePath: imagePath('210'), generation: 2 },
  { id: '211', name: 'ハリーセン', nameEn: 'Qwilfish', soundPath: soundPath('211'), imagePath: imagePath('211'), generation: 2 },
  { id: '212', name: 'ハッサム', nameEn: 'Scizor', soundPath: soundPath('212'), imagePath: imagePath('212'), generation: 2 },
  { id: '213', name: 'ツボツボ', nameEn: 'Shuckle', soundPath: soundPath('213'), imagePath: imagePath('213'), generation: 2 },
  { id: '214', name: 'ヘラクロス', nameEn: 'Heracross', soundPath: soundPath('214'), imagePath: imagePath('214'), generation: 2 },
  { id: '215', name: 'ニューラ', nameEn: 'Sneasel', soundPath: soundPath('215'), imagePath: imagePath('215'), generation: 2 },
  { id: '216', name: 'ヒメグマ', nameEn: 'Teddiursa', soundPath: soundPath('216'), imagePath: imagePath('216'), generation: 2 },
  { id: '217', name: 'リングマ', nameEn: 'Ursaring', soundPath: soundPath('217'), imagePath: imagePath('217'), generation: 2 },
  { id: '218', name: 'マグマッグ', nameEn: 'Slugma', soundPath: soundPath('218'), imagePath: imagePath('218'), generation: 2 },
  { id: '219', name: 'マグカルゴ', nameEn: 'Magcargo', soundPath: soundPath('219'), imagePath: imagePath('219'), generation: 2 },
  { id: '220', name: 'ウリムー', nameEn: 'Swinub', soundPath: soundPath('220'), imagePath: imagePath('220'), generation: 2 },
  { id: '221', name: 'イノムー', nameEn: 'Piloswine', soundPath: soundPath('221'), imagePath: imagePath('221'), generation: 2 },
  { id: '222', name: 'サニーゴ', nameEn: 'Corsola', soundPath: soundPath('222'), imagePath: imagePath('222'), generation: 2 },
  { id: '223', name: 'テッポウオ', nameEn: 'Remoraid', soundPath: soundPath('223'), imagePath: imagePath('223'), generation: 2 },
  { id: '224', name: 'オクタン', nameEn: 'Octillery', soundPath: soundPath('224'), imagePath: imagePath('224'), generation: 2 },
  { id: '225', name: 'デリバード', nameEn: 'Delibird', soundPath: soundPath('225'), imagePath: imagePath('225'), generation: 2 },
  { id: '226', name: 'マンタイン', nameEn: 'Mantine', soundPath: soundPath('226'), imagePath: imagePath('226'), generation: 2 },
  { id: '227', name: 'エアームド', nameEn: 'Skarmory', soundPath: soundPath('227'), imagePath: imagePath('227'), generation: 2 },
  { id: '228', name: 'デルビル', nameEn: 'Houndour', soundPath: soundPath('228'), imagePath: imagePath('228'), generation: 2 },
  { id: '229', name: 'ヘルガー', nameEn: 'Houndoom', soundPath: soundPath('229'), imagePath: imagePath('229'), generation: 2 },
  { id: '230', name: 'キングドラ', nameEn: 'Kingdra', soundPath: soundPath('230'), imagePath: imagePath('230'), generation: 2 },
  { id: '231', name: 'ゴマゾウ', nameEn: 'Phanpy', soundPath: soundPath('231'), imagePath: imagePath('231'), generation: 2 },
  { id: '232', name: 'ドンファン', nameEn: 'Donphan', soundPath: soundPath('232'), imagePath: imagePath('232'), generation: 2 },
  { id: '233', name: 'ポリゴン２', nameEn: 'Porygon2', soundPath: soundPath('233'), imagePath: imagePath('233'), generation: 2 },
  { id: '234', name: 'オドシシ', nameEn: 'Stantler', soundPath: soundPath('234'), imagePath: imagePath('234'), generation: 2 },
  { id: '235', name: 'ドーブル', nameEn: 'Smeargle', soundPath: soundPath('235'), imagePath: imagePath('235'), generation: 2 },
  { id: '236', name: 'バルキー', nameEn: 'Tyrogue', soundPath: soundPath('236'), imagePath: imagePath('236'), generation: 2 },
  { id: '237', name: 'カポエラー', nameEn: 'Hitmontop', soundPath: soundPath('237'), imagePath: imagePath('237'), generation: 2 },
  { id: '238', name: 'ムチュール', nameEn: 'Smoochum', soundPath: soundPath('238'), imagePath: imagePath('238'), generation: 2 },
  { id: '239', name: 'エレキッド', nameEn: 'Elekid', soundPath: soundPath('239'), imagePath: imagePath('239'), generation: 2 },
  { id: '240', name: 'ブビィ', nameEn: 'Magby', soundPath: soundPath('240'), imagePath: imagePath('240'), generation: 2 },
  { id: '241', name: 'ミルタンク', nameEn: 'Miltank', soundPath: soundPath('241'), imagePath: imagePath('241'), generation: 2 },
  { id: '242', name: 'ハピナス', nameEn: 'Blissey', soundPath: soundPath('242'), imagePath: imagePath('242'), generation: 2 },
  { id: '243', name: 'ライコウ', nameEn: 'Raikou', soundPath: soundPath('243'), imagePath: imagePath('243'), generation: 2 },
  { id: '244', name: 'エンテイ', nameEn: 'Entei', soundPath: soundPath('244'), imagePath: imagePath('244'), generation: 2 },
  { id: '245', name: 'スイクン', nameEn: 'Suicune', soundPath: soundPath('245'), imagePath: imagePath('245'), generation: 2 },
  { id: '246', name: 'ヨーギラス', nameEn: 'Larvitar', soundPath: soundPath('246'), imagePath: imagePath('246'), generation: 2 },
  { id: '247', name: 'サナギラス', nameEn: 'Pupitar', soundPath: soundPath('247'), imagePath: imagePath('247'), generation: 2 },
  { id: '248', name: 'バンギラス', nameEn: 'Tyranitar', soundPath: soundPath('248'), imagePath: imagePath('248'), generation: 2 },
  { id: '249', name: 'ルギア', nameEn: 'Lugia', soundPath: soundPath('249'), imagePath: imagePath('249'), generation: 2 },
  { id: '250', name: 'ホウオウ', nameEn: 'Ho-Oh', soundPath: soundPath('250'), imagePath: imagePath('250'), generation: 2 },
  { id: '251', name: 'セレビィ', nameEn: 'Celebi', soundPath: soundPath('251'), imagePath: imagePath('251'), generation: 2 },

  // === 第3世代 (252-386) ===
  { id: '252', name: 'キモリ', nameEn: 'Treecko', soundPath: soundPath('252'), imagePath: imagePath('252'), generation: 3 },
  { id: '253', name: 'ジュプトル', nameEn: 'Grovyle', soundPath: soundPath('253'), imagePath: imagePath('253'), generation: 3 },
  { id: '254', name: 'ジュカイン', nameEn: 'Sceptile', soundPath: soundPath('254'), imagePath: imagePath('254'), generation: 3 },
  { id: '255', name: 'アチャモ', nameEn: 'Torchic', soundPath: soundPath('255'), imagePath: imagePath('255'), generation: 3 },
  { id: '256', name: 'ワカシャモ', nameEn: 'Combusken', soundPath: soundPath('256'), imagePath: imagePath('256'), generation: 3 },
  { id: '257', name: 'バシャーモ', nameEn: 'Blaziken', soundPath: soundPath('257'), imagePath: imagePath('257'), generation: 3 },
  { id: '258', name: 'ミズゴロウ', nameEn: 'Mudkip', soundPath: soundPath('258'), imagePath: imagePath('258'), generation: 3 },
  { id: '259', name: 'ヌマクロー', nameEn: 'Marshtomp', soundPath: soundPath('259'), imagePath: imagePath('259'), generation: 3 },
  { id: '260', name: 'ラグラージ', nameEn: 'Swampert', soundPath: soundPath('260'), imagePath: imagePath('260'), generation: 3 },
  { id: '261', name: 'ポチエナ', nameEn: 'Poochyena', soundPath: soundPath('261'), imagePath: imagePath('261'), generation: 3 },
  { id: '262', name: 'グラエナ', nameEn: 'Mightyena', soundPath: soundPath('262'), imagePath: imagePath('262'), generation: 3 },
  { id: '263', name: 'ジグザグマ', nameEn: 'Zigzagoon', soundPath: soundPath('263'), imagePath: imagePath('263'), generation: 3 },
  { id: '264', name: 'マッスグマ', nameEn: 'Linoone', soundPath: soundPath('264'), imagePath: imagePath('264'), generation: 3 },
  { id: '265', name: 'ケムッソ', nameEn: 'Wurmple', soundPath: soundPath('265'), imagePath: imagePath('265'), generation: 3 },
  { id: '266', name: 'カラサリス', nameEn: 'Silcoon', soundPath: soundPath('266'), imagePath: imagePath('266'), generation: 3 },
  { id: '267', name: 'アゲハント', nameEn: 'Beautifly', soundPath: soundPath('267'), imagePath: imagePath('267'), generation: 3 },
  { id: '268', name: 'マユルド', nameEn: 'Cascoon', soundPath: soundPath('268'), imagePath: imagePath('268'), generation: 3 },
  { id: '269', name: 'ドクケイル', nameEn: 'Dustox', soundPath: soundPath('269'), imagePath: imagePath('269'), generation: 3 },
  { id: '270', name: 'ハスボー', nameEn: 'Lotad', soundPath: soundPath('270'), imagePath: imagePath('270'), generation: 3 },
  { id: '271', name: 'ハスブレロ', nameEn: 'Lombre', soundPath: soundPath('271'), imagePath: imagePath('271'), generation: 3 },
  { id: '272', name: 'ルンパッパ', nameEn: 'Ludicolo', soundPath: soundPath('272'), imagePath: imagePath('272'), generation: 3 },
  { id: '273', name: 'タネボー', nameEn: 'Seedot', soundPath: soundPath('273'), imagePath: imagePath('273'), generation: 3 },
  { id: '274', name: 'コノハナ', nameEn: 'Nuzleaf', soundPath: soundPath('274'), imagePath: imagePath('274'), generation: 3 },
  { id: '275', name: 'ダーテング', nameEn: 'Shiftry', soundPath: soundPath('275'), imagePath: imagePath('275'), generation: 3 },
  { id: '276', name: 'スバメ', nameEn: 'Taillow', soundPath: soundPath('276'), imagePath: imagePath('276'), generation: 3 },
  { id: '277', name: 'オオスバメ', nameEn: 'Swellow', soundPath: soundPath('277'), imagePath: imagePath('277'), generation: 3 },
  { id: '278', name: 'キャモメ', nameEn: 'Wingull', soundPath: soundPath('278'), imagePath: imagePath('278'), generation: 3 },
  { id: '279', name: 'ペリッパー', nameEn: 'Pelipper', soundPath: soundPath('279'), imagePath: imagePath('279'), generation: 3 },
  { id: '280', name: 'ラルトス', nameEn: 'Ralts', soundPath: soundPath('280'), imagePath: imagePath('280'), generation: 3 },
  { id: '281', name: 'キルリア', nameEn: 'Kirlia', soundPath: soundPath('281'), imagePath: imagePath('281'), generation: 3 },
  { id: '282', name: 'サーナイト', nameEn: 'Gardevoir', soundPath: soundPath('282'), imagePath: imagePath('282'), generation: 3 },
  { id: '283', name: 'アメタマ', nameEn: 'Surskit', soundPath: soundPath('283'), imagePath: imagePath('283'), generation: 3 },
  { id: '284', name: 'アメモース', nameEn: 'Masquerain', soundPath: soundPath('284'), imagePath: imagePath('284'), generation: 3 },
  { id: '285', name: 'キノココ', nameEn: 'Shroomish', soundPath: soundPath('285'), imagePath: imagePath('285'), generation: 3 },
  { id: '286', name: 'キノガッサ', nameEn: 'Breloom', soundPath: soundPath('286'), imagePath: imagePath('286'), generation: 3 },
  { id: '287', name: 'ナマケロ', nameEn: 'Slakoth', soundPath: soundPath('287'), imagePath: imagePath('287'), generation: 3 },
  { id: '288', name: 'ヤルキモノ', nameEn: 'Vigoroth', soundPath: soundPath('288'), imagePath: imagePath('288'), generation: 3 },
  { id: '289', name: 'ケッキング', nameEn: 'Slaking', soundPath: soundPath('289'), imagePath: imagePath('289'), generation: 3 },
  { id: '290', name: 'ツチニン', nameEn: 'Nincada', soundPath: soundPath('290'), imagePath: imagePath('290'), generation: 3 },
  { id: '291', name: 'テッカニン', nameEn: 'Ninjask', soundPath: soundPath('291'), imagePath: imagePath('291'), generation: 3 },
  { id: '292', name: 'ヌケニン', nameEn: 'Shedinja', soundPath: soundPath('292'), imagePath: imagePath('292'), generation: 3 },
  { id: '293', name: 'ゴニョニョ', nameEn: 'Whismur', soundPath: soundPath('293'), imagePath: imagePath('293'), generation: 3 },
  { id: '294', name: 'ドゴーム', nameEn: 'Loudred', soundPath: soundPath('294'), imagePath: imagePath('294'), generation: 3 },
  { id: '295', name: 'バクオング', nameEn: 'Exploud', soundPath: soundPath('295'), imagePath: imagePath('295'), generation: 3 },
  { id: '296', name: 'マクノシタ', nameEn: 'Makuhita', soundPath: soundPath('296'), imagePath: imagePath('296'), generation: 3 },
  { id: '297', name: 'ハリテヤマ', nameEn: 'Hariyama', soundPath: soundPath('297'), imagePath: imagePath('297'), generation: 3 },
  { id: '298', name: 'ルリリ', nameEn: 'Azurill', soundPath: soundPath('298'), imagePath: imagePath('298'), generation: 3 },
  { id: '299', name: 'ノズパス', nameEn: 'Nosepass', soundPath: soundPath('299'), imagePath: imagePath('299'), generation: 3 },
  { id: '300', name: 'エネコ', nameEn: 'Skitty', soundPath: soundPath('300'), imagePath: imagePath('300'), generation: 3 },
  { id: '301', name: 'エネコロロ', nameEn: 'Delcatty', soundPath: soundPath('301'), imagePath: imagePath('301'), generation: 3 },
  { id: '302', name: 'ヤミラミ', nameEn: 'Sableye', soundPath: soundPath('302'), imagePath: imagePath('302'), generation: 3 },
  { id: '303', name: 'クチート', nameEn: 'Mawile', soundPath: soundPath('303'), imagePath: imagePath('303'), generation: 3 },
  { id: '304', name: 'ココドラ', nameEn: 'Aron', soundPath: soundPath('304'), imagePath: imagePath('304'), generation: 3 },
  { id: '305', name: 'コドラ', nameEn: 'Lairon', soundPath: soundPath('305'), imagePath: imagePath('305'), generation: 3 },
  { id: '306', name: 'ボスゴドラ', nameEn: 'Aggron', soundPath: soundPath('306'), imagePath: imagePath('306'), generation: 3 },
  { id: '307', name: 'アサナン', nameEn: 'Meditite', soundPath: soundPath('307'), imagePath: imagePath('307'), generation: 3 },
  { id: '308', name: 'チャーレム', nameEn: 'Medicham', soundPath: soundPath('308'), imagePath: imagePath('308'), generation: 3 },
  { id: '309', name: 'ラクライ', nameEn: 'Electrike', soundPath: soundPath('309'), imagePath: imagePath('309'), generation: 3 },
  { id: '310', name: 'ライボルト', nameEn: 'Manectric', soundPath: soundPath('310'), imagePath: imagePath('310'), generation: 3 },
  { id: '311', name: 'プラスル', nameEn: 'Plusle', soundPath: soundPath('311'), imagePath: imagePath('311'), generation: 3 },
  { id: '312', name: 'マイナン', nameEn: 'Minun', soundPath: soundPath('312'), imagePath: imagePath('312'), generation: 3 },
  { id: '313', name: 'バルビート', nameEn: 'Volbeat', soundPath: soundPath('313'), imagePath: imagePath('313'), generation: 3 },
  { id: '314', name: 'イルミーゼ', nameEn: 'Illumise', soundPath: soundPath('314'), imagePath: imagePath('314'), generation: 3 },
  { id: '315', name: 'ロゼリア', nameEn: 'Roselia', soundPath: soundPath('315'), imagePath: imagePath('315'), generation: 3 },
  { id: '316', name: 'ゴクリン', nameEn: 'Gulpin', soundPath: soundPath('316'), imagePath: imagePath('316'), generation: 3 },
  { id: '317', name: 'マルノーム', nameEn: 'Swalot', soundPath: soundPath('317'), imagePath: imagePath('317'), generation: 3 },
  { id: '318', name: 'キバニア', nameEn: 'Carvanha', soundPath: soundPath('318'), imagePath: imagePath('318'), generation: 3 },
  { id: '319', name: 'サメハダー', nameEn: 'Sharpedo', soundPath: soundPath('319'), imagePath: imagePath('319'), generation: 3 },
  { id: '320', name: 'ホエルコ', nameEn: 'Wailmer', soundPath: soundPath('320'), imagePath: imagePath('320'), generation: 3 },
  { id: '321', name: 'ホエルオー', nameEn: 'Wailord', soundPath: soundPath('321'), imagePath: imagePath('321'), generation: 3 },
  { id: '322', name: 'ドンメル', nameEn: 'Numel', soundPath: soundPath('322'), imagePath: imagePath('322'), generation: 3 },
  { id: '323', name: 'バクーダ', nameEn: 'Camerupt', soundPath: soundPath('323'), imagePath: imagePath('323'), generation: 3 },
  { id: '324', name: 'コータス', nameEn: 'Torkoal', soundPath: soundPath('324'), imagePath: imagePath('324'), generation: 3 },
  { id: '325', name: 'バネブー', nameEn: 'Spoink', soundPath: soundPath('325'), imagePath: imagePath('325'), generation: 3 },
  { id: '326', name: 'ブーピッグ', nameEn: 'Grumpig', soundPath: soundPath('326'), imagePath: imagePath('326'), generation: 3 },
  { id: '327', name: 'パッチール', nameEn: 'Spinda', soundPath: soundPath('327'), imagePath: imagePath('327'), generation: 3 },
  { id: '328', name: 'ナックラー', nameEn: 'Trapinch', soundPath: soundPath('328'), imagePath: imagePath('328'), generation: 3 },
  { id: '329', name: 'ビブラーバ', nameEn: 'Vibrava', soundPath: soundPath('329'), imagePath: imagePath('329'), generation: 3 },
  { id: '330', name: 'フライゴン', nameEn: 'Flygon', soundPath: soundPath('330'), imagePath: imagePath('330'), generation: 3 },
  { id: '331', name: 'サボネア', nameEn: 'Cacnea', soundPath: soundPath('331'), imagePath: imagePath('331'), generation: 3 },
  { id: '332', name: 'ノクタス', nameEn: 'Cacturne', soundPath: soundPath('332'), imagePath: imagePath('332'), generation: 3 },
  { id: '333', name: 'チルット', nameEn: 'Swablu', soundPath: soundPath('333'), imagePath: imagePath('333'), generation: 3 },
  { id: '334', name: 'チルタリス', nameEn: 'Altaria', soundPath: soundPath('334'), imagePath: imagePath('334'), generation: 3 },
  { id: '335', name: 'ザングース', nameEn: 'Zangoose', soundPath: soundPath('335'), imagePath: imagePath('335'), generation: 3 },
  { id: '336', name: 'ハブネーク', nameEn: 'Seviper', soundPath: soundPath('336'), imagePath: imagePath('336'), generation: 3 },
  { id: '337', name: 'ルナトーン', nameEn: 'Lunatone', soundPath: soundPath('337'), imagePath: imagePath('337'), generation: 3 },
  { id: '338', name: 'ソルロック', nameEn: 'Solrock', soundPath: soundPath('338'), imagePath: imagePath('338'), generation: 3 },
  { id: '339', name: 'ドジョッチ', nameEn: 'Barboach', soundPath: soundPath('339'), imagePath: imagePath('339'), generation: 3 },
  { id: '340', name: 'ナマズン', nameEn: 'Whiscash', soundPath: soundPath('340'), imagePath: imagePath('340'), generation: 3 },
  { id: '341', name: 'ヘイガニ', nameEn: 'Corphish', soundPath: soundPath('341'), imagePath: imagePath('341'), generation: 3 },
  { id: '342', name: 'シザリガー', nameEn: 'Crawdaunt', soundPath: soundPath('342'), imagePath: imagePath('342'), generation: 3 },
  { id: '343', name: 'ヤジロン', nameEn: 'Baltoy', soundPath: soundPath('343'), imagePath: imagePath('343'), generation: 3 },
  { id: '344', name: 'ネンドール', nameEn: 'Claydol', soundPath: soundPath('344'), imagePath: imagePath('344'), generation: 3 },
  { id: '345', name: 'リリーラ', nameEn: 'Lileep', soundPath: soundPath('345'), imagePath: imagePath('345'), generation: 3 },
  { id: '346', name: 'ユレイドル', nameEn: 'Cradily', soundPath: soundPath('346'), imagePath: imagePath('346'), generation: 3 },
  { id: '347', name: 'アノプス', nameEn: 'Anorith', soundPath: soundPath('347'), imagePath: imagePath('347'), generation: 3 },
  { id: '348', name: 'アーマルド', nameEn: 'Armaldo', soundPath: soundPath('348'), imagePath: imagePath('348'), generation: 3 },
  { id: '349', name: 'ヒンバス', nameEn: 'Feebas', soundPath: soundPath('349'), imagePath: imagePath('349'), generation: 3 },
  { id: '350', name: 'ミロカロス', nameEn: 'Milotic', soundPath: soundPath('350'), imagePath: imagePath('350'), generation: 3 },
  { id: '351', name: 'ポワルン', nameEn: 'Castform', soundPath: soundPath('351'), imagePath: imagePath('351'), generation: 3 },
  { id: '352', name: 'カクレオン', nameEn: 'Kecleon', soundPath: soundPath('352'), imagePath: imagePath('352'), generation: 3 },
  { id: '353', name: 'カゲボウズ', nameEn: 'Shuppet', soundPath: soundPath('353'), imagePath: imagePath('353'), generation: 3 },
  { id: '354', name: 'ジュペッタ', nameEn: 'Banette', soundPath: soundPath('354'), imagePath: imagePath('354'), generation: 3 },
  { id: '355', name: 'ヨマワル', nameEn: 'Duskull', soundPath: soundPath('355'), imagePath: imagePath('355'), generation: 3 },
  { id: '356', name: 'サマヨール', nameEn: 'Dusclops', soundPath: soundPath('356'), imagePath: imagePath('356'), generation: 3 },
  { id: '357', name: 'トロピウス', nameEn: 'Tropius', soundPath: soundPath('357'), imagePath: imagePath('357'), generation: 3 },
  { id: '358', name: 'チリーン', nameEn: 'Chimecho', soundPath: soundPath('358'), imagePath: imagePath('358'), generation: 3 },
  { id: '359', name: 'アブソル', nameEn: 'Absol', soundPath: soundPath('359'), imagePath: imagePath('359'), generation: 3 },
  { id: '360', name: 'ソーナノ', nameEn: 'Wynaut', soundPath: soundPath('360'), imagePath: imagePath('360'), generation: 3 },
  { id: '361', name: 'ユキワラシ', nameEn: 'Snorunt', soundPath: soundPath('361'), imagePath: imagePath('361'), generation: 3 },
  { id: '362', name: 'オニゴーリ', nameEn: 'Glalie', soundPath: soundPath('362'), imagePath: imagePath('362'), generation: 3 },
  { id: '363', name: 'タマザラシ', nameEn: 'Spheal', soundPath: soundPath('363'), imagePath: imagePath('363'), generation: 3 },
  { id: '364', name: 'トドグラー', nameEn: 'Sealeo', soundPath: soundPath('364'), imagePath: imagePath('364'), generation: 3 },
  { id: '365', name: 'トドゼルガ', nameEn: 'Walrein', soundPath: soundPath('365'), imagePath: imagePath('365'), generation: 3 },
  { id: '366', name: 'パールル', nameEn: 'Clamperl', soundPath: soundPath('366'), imagePath: imagePath('366'), generation: 3 },
  { id: '367', name: 'ハンテール', nameEn: 'Huntail', soundPath: soundPath('367'), imagePath: imagePath('367'), generation: 3 },
  { id: '368', name: 'サクラビス', nameEn: 'Gorebyss', soundPath: soundPath('368'), imagePath: imagePath('368'), generation: 3 },
  { id: '369', name: 'ジーランス', nameEn: 'Relicanth', soundPath: soundPath('369'), imagePath: imagePath('369'), generation: 3 },
  { id: '370', name: 'ラブカス', nameEn: 'Luvdisc', soundPath: soundPath('370'), imagePath: imagePath('370'), generation: 3 },
  { id: '371', name: 'タツベイ', nameEn: 'Bagon', soundPath: soundPath('371'), imagePath: imagePath('371'), generation: 3 },
  { id: '372', name: 'コモルー', nameEn: 'Shelgon', soundPath: soundPath('372'), imagePath: imagePath('372'), generation: 3 },
  { id: '373', name: 'ボーマンダ', nameEn: 'Salamence', soundPath: soundPath('373'), imagePath: imagePath('373'), generation: 3 },
  { id: '374', name: 'ダンバル', nameEn: 'Beldum', soundPath: soundPath('374'), imagePath: imagePath('374'), generation: 3 },
  { id: '375', name: 'メタング', nameEn: 'Metang', soundPath: soundPath('375'), imagePath: imagePath('375'), generation: 3 },
  { id: '376', name: 'メタグロス', nameEn: 'Metagross', soundPath: soundPath('376'), imagePath: imagePath('376'), generation: 3 },
  { id: '377', name: 'レジロック', nameEn: 'Regirock', soundPath: soundPath('377'), imagePath: imagePath('377'), generation: 3 },
  { id: '378', name: 'レジアイス', nameEn: 'Regice', soundPath: soundPath('378'), imagePath: imagePath('378'), generation: 3 },
  { id: '379', name: 'レジスチル', nameEn: 'Registeel', soundPath: soundPath('379'), imagePath: imagePath('379'), generation: 3 },
  { id: '380', name: 'ラティアス', nameEn: 'Latias', soundPath: soundPath('380'), imagePath: imagePath('380'), generation: 3 },
  { id: '381', name: 'ラティオス', nameEn: 'Latios', soundPath: soundPath('381'), imagePath: imagePath('381'), generation: 3 },
  { id: '382', name: 'カイオーガ', nameEn: 'Kyogre', soundPath: soundPath('382'), imagePath: imagePath('382'), generation: 3 },
  { id: '383', name: 'グラードン', nameEn: 'Groudon', soundPath: soundPath('383'), imagePath: imagePath('383'), generation: 3 },
  { id: '384', name: 'レックウザ', nameEn: 'Rayquaza', soundPath: soundPath('384'), imagePath: imagePath('384'), generation: 3 },
  { id: '385', name: 'ジラーチ', nameEn: 'Jirachi', soundPath: soundPath('385'), imagePath: imagePath('385'), generation: 3 },
  { id: '386', name: 'デオキシス', nameEn: 'Deoxys', soundPath: soundPath('386'), imagePath: imagePath('386'), generation: 3 },

  // === 第4世代 (387-493) ===
  { id: '387', name: 'ナエトル', nameEn: 'Turtwig', soundPath: soundPath('387'), imagePath: imagePath('387'), generation: 4 },
  { id: '388', name: 'ハヤシガメ', nameEn: 'Grotle', soundPath: soundPath('388'), imagePath: imagePath('388'), generation: 4 },
  { id: '389', name: 'ドダイトス', nameEn: 'Torterra', soundPath: soundPath('389'), imagePath: imagePath('389'), generation: 4 },
  { id: '390', name: 'ヒコザル', nameEn: 'Chimchar', soundPath: soundPath('390'), imagePath: imagePath('390'), generation: 4 },
  { id: '391', name: 'モウカザル', nameEn: 'Monferno', soundPath: soundPath('391'), imagePath: imagePath('391'), generation: 4 },
  { id: '392', name: 'ゴウカザル', nameEn: 'Infernape', soundPath: soundPath('392'), imagePath: imagePath('392'), generation: 4 },
  { id: '393', name: 'ポッチャマ', nameEn: 'Piplup', soundPath: soundPath('393'), imagePath: imagePath('393'), generation: 4 },
  { id: '394', name: 'ポッタイシ', nameEn: 'Prinplup', soundPath: soundPath('394'), imagePath: imagePath('394'), generation: 4 },
  { id: '395', name: 'エンペルト', nameEn: 'Empoleon', soundPath: soundPath('395'), imagePath: imagePath('395'), generation: 4 },
  { id: '396', name: 'ムックル', nameEn: 'Starly', soundPath: soundPath('396'), imagePath: imagePath('396'), generation: 4 },
  { id: '397', name: 'ムクバード', nameEn: 'Staravia', soundPath: soundPath('397'), imagePath: imagePath('397'), generation: 4 },
  { id: '398', name: 'ムクホーク', nameEn: 'Staraptor', soundPath: soundPath('398'), imagePath: imagePath('398'), generation: 4 },
  { id: '399', name: 'ビッパ', nameEn: 'Bidoof', soundPath: soundPath('399'), imagePath: imagePath('399'), generation: 4 },
  { id: '400', name: 'ビーダル', nameEn: 'Bibarel', soundPath: soundPath('400'), imagePath: imagePath('400'), generation: 4 },
  { id: '401', name: 'コロボーシ', nameEn: 'Kricketot', soundPath: soundPath('401'), imagePath: imagePath('401'), generation: 4 },
  { id: '402', name: 'コロトック', nameEn: 'Kricketune', soundPath: soundPath('402'), imagePath: imagePath('402'), generation: 4 },
  { id: '403', name: 'コリンク', nameEn: 'Shinx', soundPath: soundPath('403'), imagePath: imagePath('403'), generation: 4 },
  { id: '404', name: 'ルクシオ', nameEn: 'Luxio', soundPath: soundPath('404'), imagePath: imagePath('404'), generation: 4 },
  { id: '405', name: 'レントラー', nameEn: 'Luxray', soundPath: soundPath('405'), imagePath: imagePath('405'), generation: 4 },
  { id: '406', name: 'スボミー', nameEn: 'Budew', soundPath: soundPath('406'), imagePath: imagePath('406'), generation: 4 },
  { id: '407', name: 'ロズレイド', nameEn: 'Roserade', soundPath: soundPath('407'), imagePath: imagePath('407'), generation: 4 },
  { id: '408', name: 'ズガイドス', nameEn: 'Cranidos', soundPath: soundPath('408'), imagePath: imagePath('408'), generation: 4 },
  { id: '409', name: 'ラムパルド', nameEn: 'Rampardos', soundPath: soundPath('409'), imagePath: imagePath('409'), generation: 4 },
  { id: '410', name: 'タテトプス', nameEn: 'Shieldon', soundPath: soundPath('410'), imagePath: imagePath('410'), generation: 4 },
  { id: '411', name: 'トリデプス', nameEn: 'Bastiodon', soundPath: soundPath('411'), imagePath: imagePath('411'), generation: 4 },
  { id: '412', name: 'ミノムッチ', nameEn: 'Burmy', soundPath: soundPath('412'), imagePath: imagePath('412'), generation: 4 },
  { id: '413', name: 'ミノマダム', nameEn: 'Wormadam', soundPath: soundPath('413'), imagePath: imagePath('413'), generation: 4 },
  { id: '414', name: 'ガーメイル', nameEn: 'Mothim', soundPath: soundPath('414'), imagePath: imagePath('414'), generation: 4 },
  { id: '415', name: 'ミツハニー', nameEn: 'Combee', soundPath: soundPath('415'), imagePath: imagePath('415'), generation: 4 },
  { id: '416', name: 'ビークイン', nameEn: 'Vespiquen', soundPath: soundPath('416'), imagePath: imagePath('416'), generation: 4 },
  { id: '417', name: 'パチリス', nameEn: 'Pachirisu', soundPath: soundPath('417'), imagePath: imagePath('417'), generation: 4 },
  { id: '418', name: 'ブイゼル', nameEn: 'Buizel', soundPath: soundPath('418'), imagePath: imagePath('418'), generation: 4 },
  { id: '419', name: 'フローゼル', nameEn: 'Floatzel', soundPath: soundPath('419'), imagePath: imagePath('419'), generation: 4 },
  { id: '420', name: 'チェリンボ', nameEn: 'Cherubi', soundPath: soundPath('420'), imagePath: imagePath('420'), generation: 4 },
  { id: '421', name: 'チェリム', nameEn: 'Cherrim', soundPath: soundPath('421'), imagePath: imagePath('421'), generation: 4 },
  { id: '422', name: 'カラナクシ', nameEn: 'Shellos', soundPath: soundPath('422'), imagePath: imagePath('422'), generation: 4 },
  { id: '423', name: 'トリトドン', nameEn: 'Gastrodon', soundPath: soundPath('423'), imagePath: imagePath('423'), generation: 4 },
  { id: '424', name: 'エテボース', nameEn: 'Ambipom', soundPath: soundPath('424'), imagePath: imagePath('424'), generation: 4 },
  { id: '425', name: 'フワンテ', nameEn: 'Drifloon', soundPath: soundPath('425'), imagePath: imagePath('425'), generation: 4 },
  { id: '426', name: 'フワライド', nameEn: 'Drifblim', soundPath: soundPath('426'), imagePath: imagePath('426'), generation: 4 },
  { id: '427', name: 'ミミロル', nameEn: 'Buneary', soundPath: soundPath('427'), imagePath: imagePath('427'), generation: 4 },
  { id: '428', name: 'ミミロップ', nameEn: 'Lopunny', soundPath: soundPath('428'), imagePath: imagePath('428'), generation: 4 },
  { id: '429', name: 'ムウマージ', nameEn: 'Mismagius', soundPath: soundPath('429'), imagePath: imagePath('429'), generation: 4 },
  { id: '430', name: 'ドンカラス', nameEn: 'Honchkrow', soundPath: soundPath('430'), imagePath: imagePath('430'), generation: 4 },
  { id: '431', name: 'ニャルマー', nameEn: 'Glameow', soundPath: soundPath('431'), imagePath: imagePath('431'), generation: 4 },
  { id: '432', name: 'ブニャット', nameEn: 'Purugly', soundPath: soundPath('432'), imagePath: imagePath('432'), generation: 4 },
  { id: '433', name: 'リーシャン', nameEn: 'Chingling', soundPath: soundPath('433'), imagePath: imagePath('433'), generation: 4 },
  { id: '434', name: 'スカンプー', nameEn: 'Stunky', soundPath: soundPath('434'), imagePath: imagePath('434'), generation: 4 },
  { id: '435', name: 'スカタンク', nameEn: 'Skuntank', soundPath: soundPath('435'), imagePath: imagePath('435'), generation: 4 },
  { id: '436', name: 'ドーミラー', nameEn: 'Bronzor', soundPath: soundPath('436'), imagePath: imagePath('436'), generation: 4 },
  { id: '437', name: 'ドータクン', nameEn: 'Bronzong', soundPath: soundPath('437'), imagePath: imagePath('437'), generation: 4 },
  { id: '438', name: 'ウソハチ', nameEn: 'Bonsly', soundPath: soundPath('438'), imagePath: imagePath('438'), generation: 4 },
  { id: '439', name: 'マネネ', nameEn: 'Mime Jr.', soundPath: soundPath('439'), imagePath: imagePath('439'), generation: 4 },
  { id: '440', name: 'ピンプク', nameEn: 'Happiny', soundPath: soundPath('440'), imagePath: imagePath('440'), generation: 4 },
  { id: '441', name: 'ペラップ', nameEn: 'Chatot', soundPath: soundPath('441'), imagePath: imagePath('441'), generation: 4 },
  { id: '442', name: 'ミカルゲ', nameEn: 'Spiritomb', soundPath: soundPath('442'), imagePath: imagePath('442'), generation: 4 },
  { id: '443', name: 'フカマル', nameEn: 'Gible', soundPath: soundPath('443'), imagePath: imagePath('443'), generation: 4 },
  { id: '444', name: 'ガバイト', nameEn: 'Gabite', soundPath: soundPath('444'), imagePath: imagePath('444'), generation: 4 },
  { id: '445', name: 'ガブリアス', nameEn: 'Garchomp', soundPath: soundPath('445'), imagePath: imagePath('445'), generation: 4 },
  { id: '446', name: 'ゴンベ', nameEn: 'Munchlax', soundPath: soundPath('446'), imagePath: imagePath('446'), generation: 4 },
  { id: '447', name: 'リオル', nameEn: 'Riolu', soundPath: soundPath('447'), imagePath: imagePath('447'), generation: 4 },
  { id: '448', name: 'ルカリオ', nameEn: 'Lucario', soundPath: soundPath('448'), imagePath: imagePath('448'), generation: 4 },
  { id: '449', name: 'ヒポポタス', nameEn: 'Hippopotas', soundPath: soundPath('449'), imagePath: imagePath('449'), generation: 4 },
  { id: '450', name: 'カバルドン', nameEn: 'Hippowdon', soundPath: soundPath('450'), imagePath: imagePath('450'), generation: 4 },
  { id: '451', name: 'スコルピ', nameEn: 'Skorupi', soundPath: soundPath('451'), imagePath: imagePath('451'), generation: 4 },
  { id: '452', name: 'ドラピオン', nameEn: 'Drapion', soundPath: soundPath('452'), imagePath: imagePath('452'), generation: 4 },
  { id: '453', name: 'グレッグル', nameEn: 'Croagunk', soundPath: soundPath('453'), imagePath: imagePath('453'), generation: 4 },
  { id: '454', name: 'ドクロッグ', nameEn: 'Toxicroak', soundPath: soundPath('454'), imagePath: imagePath('454'), generation: 4 },
  { id: '455', name: 'マスキッパ', nameEn: 'Carnivine', soundPath: soundPath('455'), imagePath: imagePath('455'), generation: 4 },
  { id: '456', name: 'ケイコウオ', nameEn: 'Finneon', soundPath: soundPath('456'), imagePath: imagePath('456'), generation: 4 },
  { id: '457', name: 'ネオラント', nameEn: 'Lumineon', soundPath: soundPath('457'), imagePath: imagePath('457'), generation: 4 },
  { id: '458', name: 'タマンタ', nameEn: 'Mantyke', soundPath: soundPath('458'), imagePath: imagePath('458'), generation: 4 },
  { id: '459', name: 'ユキカブリ', nameEn: 'Snover', soundPath: soundPath('459'), imagePath: imagePath('459'), generation: 4 },
  { id: '460', name: 'ユキノオー', nameEn: 'Abomasnow', soundPath: soundPath('460'), imagePath: imagePath('460'), generation: 4 },
  { id: '461', name: 'マニューラ', nameEn: 'Weavile', soundPath: soundPath('461'), imagePath: imagePath('461'), generation: 4 },
  { id: '462', name: 'ジバコイル', nameEn: 'Magnezone', soundPath: soundPath('462'), imagePath: imagePath('462'), generation: 4 },
  { id: '463', name: 'ベロベルト', nameEn: 'Lickilicky', soundPath: soundPath('463'), imagePath: imagePath('463'), generation: 4 },
  { id: '464', name: 'ドサイドン', nameEn: 'Rhyperior', soundPath: soundPath('464'), imagePath: imagePath('464'), generation: 4 },
  { id: '465', name: 'モジャンボ', nameEn: 'Tangrowth', soundPath: soundPath('465'), imagePath: imagePath('465'), generation: 4 },
  { id: '466', name: 'エレキブル', nameEn: 'Electivire', soundPath: soundPath('466'), imagePath: imagePath('466'), generation: 4 },
  { id: '467', name: 'ブーバーン', nameEn: 'Magmortar', soundPath: soundPath('467'), imagePath: imagePath('467'), generation: 4 },
  { id: '468', name: 'トゲキッス', nameEn: 'Togekiss', soundPath: soundPath('468'), imagePath: imagePath('468'), generation: 4 },
  { id: '469', name: 'メガヤンマ', nameEn: 'Yanmega', soundPath: soundPath('469'), imagePath: imagePath('469'), generation: 4 },
  { id: '470', name: 'リーフィア', nameEn: 'Leafeon', soundPath: soundPath('470'), imagePath: imagePath('470'), generation: 4 },
  { id: '471', name: 'グレイシア', nameEn: 'Glaceon', soundPath: soundPath('471'), imagePath: imagePath('471'), generation: 4 },
  { id: '472', name: 'グライオン', nameEn: 'Gliscor', soundPath: soundPath('472'), imagePath: imagePath('472'), generation: 4 },
  { id: '473', name: 'マンムー', nameEn: 'Mamoswine', soundPath: soundPath('473'), imagePath: imagePath('473'), generation: 4 },
  { id: '474', name: 'ポリゴンＺ', nameEn: 'Porygon-Z', soundPath: soundPath('474'), imagePath: imagePath('474'), generation: 4 },
  { id: '475', name: 'エルレイド', nameEn: 'Gallade', soundPath: soundPath('475'), imagePath: imagePath('475'), generation: 4 },
  { id: '476', name: 'ダイノーズ', nameEn: 'Probopass', soundPath: soundPath('476'), imagePath: imagePath('476'), generation: 4 },
  { id: '477', name: 'ヨノワール', nameEn: 'Dusknoir', soundPath: soundPath('477'), imagePath: imagePath('477'), generation: 4 },
  { id: '478', name: 'ユキメノコ', nameEn: 'Froslass', soundPath: soundPath('478'), imagePath: imagePath('478'), generation: 4 },
  { id: '479', name: 'ロトム', nameEn: 'Rotom', soundPath: soundPath('479'), imagePath: imagePath('479'), generation: 4 },
  { id: '480', name: 'ユクシー', nameEn: 'Uxie', soundPath: soundPath('480'), imagePath: imagePath('480'), generation: 4 },
  { id: '481', name: 'エムリット', nameEn: 'Mesprit', soundPath: soundPath('481'), imagePath: imagePath('481'), generation: 4 },
  { id: '482', name: 'アグノム', nameEn: 'Azelf', soundPath: soundPath('482'), imagePath: imagePath('482'), generation: 4 },
  { id: '483', name: 'ディアルガ', nameEn: 'Dialga', soundPath: soundPath('483'), imagePath: imagePath('483'), generation: 4 },
  { id: '484', name: 'パルキア', nameEn: 'Palkia', soundPath: soundPath('484'), imagePath: imagePath('484'), generation: 4 },
  { id: '485', name: 'ヒードラン', nameEn: 'Heatran', soundPath: soundPath('485'), imagePath: imagePath('485'), generation: 4 },
  { id: '486', name: 'レジギガス', nameEn: 'Regigigas', soundPath: soundPath('486'), imagePath: imagePath('486'), generation: 4 },
  { id: '487', name: 'ギラティナ', nameEn: 'Giratina', soundPath: soundPath('487'), imagePath: imagePath('487'), generation: 4 },
  { id: '488', name: 'クレセリア', nameEn: 'Cresselia', soundPath: soundPath('488'), imagePath: imagePath('488'), generation: 4 },
  { id: '489', name: 'フィオネ', nameEn: 'Phione', soundPath: soundPath('489'), imagePath: imagePath('489'), generation: 4 },
  { id: '490', name: 'マナフィ', nameEn: 'Manaphy', soundPath: soundPath('490'), imagePath: imagePath('490'), generation: 4 },
  { id: '491', name: 'ダークライ', nameEn: 'Darkrai', soundPath: soundPath('491'), imagePath: imagePath('491'), generation: 4 },
  { id: '492', name: 'シェイミ', nameEn: 'Shaymin', soundPath: soundPath('492'), imagePath: imagePath('492'), generation: 4 },
  { id: '493', name: 'アルセウス', nameEn: 'Arceus', soundPath: soundPath('493'), imagePath: imagePath('493'), generation: 4 },

  // === 第5世代 (494-649) ===
  { id: '494', name: 'ビクティニ', nameEn: 'Victini', soundPath: soundPath('494'), imagePath: imagePath('494'), generation: 5 },
  { id: '495', name: 'ツタージャ', nameEn: 'Snivy', soundPath: soundPath('495'), imagePath: imagePath('495'), generation: 5 },
  { id: '496', name: 'ジャノビー', nameEn: 'Servine', soundPath: soundPath('496'), imagePath: imagePath('496'), generation: 5 },
  { id: '497', name: 'ジャローダ', nameEn: 'Serperior', soundPath: soundPath('497'), imagePath: imagePath('497'), generation: 5 },
  { id: '498', name: 'ポカブ', nameEn: 'Tepig', soundPath: soundPath('498'), imagePath: imagePath('498'), generation: 5 },
  { id: '499', name: 'チャオブー', nameEn: 'Pignite', soundPath: soundPath('499'), imagePath: imagePath('499'), generation: 5 },
  { id: '500', name: 'エンブオー', nameEn: 'Emboar', soundPath: soundPath('500'), imagePath: imagePath('500'), generation: 5 },
  { id: '501', name: 'ミジュマル', nameEn: 'Oshawott', soundPath: soundPath('501'), imagePath: imagePath('501'), generation: 5 },
  { id: '502', name: 'フタチマル', nameEn: 'Dewott', soundPath: soundPath('502'), imagePath: imagePath('502'), generation: 5 },
  { id: '503', name: 'ダイケンキ', nameEn: 'Samurott', soundPath: soundPath('503'), imagePath: imagePath('503'), generation: 5 },
  { id: '504', name: 'ミネズミ', nameEn: 'Patrat', soundPath: soundPath('504'), imagePath: imagePath('504'), generation: 5 },
  { id: '505', name: 'ミルホッグ', nameEn: 'Watchog', soundPath: soundPath('505'), imagePath: imagePath('505'), generation: 5 },
  { id: '506', name: 'ヨーテリー', nameEn: 'Lillipup', soundPath: soundPath('506'), imagePath: imagePath('506'), generation: 5 },
  { id: '507', name: 'ハーデリア', nameEn: 'Herdier', soundPath: soundPath('507'), imagePath: imagePath('507'), generation: 5 },
  { id: '508', name: 'ムーランド', nameEn: 'Stoutland', soundPath: soundPath('508'), imagePath: imagePath('508'), generation: 5 },
  { id: '509', name: 'チョロネコ', nameEn: 'Purrloin', soundPath: soundPath('509'), imagePath: imagePath('509'), generation: 5 },
  { id: '510', name: 'レパルダス', nameEn: 'Liepard', soundPath: soundPath('510'), imagePath: imagePath('510'), generation: 5 },
  { id: '511', name: 'ヤナップ', nameEn: 'Pansage', soundPath: soundPath('511'), imagePath: imagePath('511'), generation: 5 },
  { id: '512', name: 'ヤナッキー', nameEn: 'Simisage', soundPath: soundPath('512'), imagePath: imagePath('512'), generation: 5 },
  { id: '513', name: 'バオップ', nameEn: 'Pansear', soundPath: soundPath('513'), imagePath: imagePath('513'), generation: 5 },
  { id: '514', name: 'バオッキー', nameEn: 'Simisear', soundPath: soundPath('514'), imagePath: imagePath('514'), generation: 5 },
  { id: '515', name: 'ヒヤップ', nameEn: 'Panpour', soundPath: soundPath('515'), imagePath: imagePath('515'), generation: 5 },
  { id: '516', name: 'ヒヤッキー', nameEn: 'Simipour', soundPath: soundPath('516'), imagePath: imagePath('516'), generation: 5 },
  { id: '517', name: 'ムンナ', nameEn: 'Munna', soundPath: soundPath('517'), imagePath: imagePath('517'), generation: 5 },
  { id: '518', name: 'ムシャーナ', nameEn: 'Musharna', soundPath: soundPath('518'), imagePath: imagePath('518'), generation: 5 },
  { id: '519', name: 'マメパト', nameEn: 'Pidove', soundPath: soundPath('519'), imagePath: imagePath('519'), generation: 5 },
  { id: '520', name: 'ハトーボー', nameEn: 'Tranquill', soundPath: soundPath('520'), imagePath: imagePath('520'), generation: 5 },
  { id: '521', name: 'ケンホロウ', nameEn: 'Unfezant', soundPath: soundPath('521'), imagePath: imagePath('521'), generation: 5 },
  { id: '522', name: 'シママ', nameEn: 'Blitzle', soundPath: soundPath('522'), imagePath: imagePath('522'), generation: 5 },
  { id: '523', name: 'ゼブライカ', nameEn: 'Zebstrika', soundPath: soundPath('523'), imagePath: imagePath('523'), generation: 5 },
  { id: '524', name: 'ダンゴロ', nameEn: 'Roggenrola', soundPath: soundPath('524'), imagePath: imagePath('524'), generation: 5 },
  { id: '525', name: 'ガントル', nameEn: 'Boldore', soundPath: soundPath('525'), imagePath: imagePath('525'), generation: 5 },
  { id: '526', name: 'ギガイアス', nameEn: 'Gigalith', soundPath: soundPath('526'), imagePath: imagePath('526'), generation: 5 },
  { id: '527', name: 'コロモリ', nameEn: 'Woobat', soundPath: soundPath('527'), imagePath: imagePath('527'), generation: 5 },
  { id: '528', name: 'ココロモリ', nameEn: 'Swoobat', soundPath: soundPath('528'), imagePath: imagePath('528'), generation: 5 },
  { id: '529', name: 'モグリュー', nameEn: 'Drilbur', soundPath: soundPath('529'), imagePath: imagePath('529'), generation: 5 },
  { id: '530', name: 'ドリュウズ', nameEn: 'Excadrill', soundPath: soundPath('530'), imagePath: imagePath('530'), generation: 5 },
  { id: '531', name: 'タブンネ', nameEn: 'Audino', soundPath: soundPath('531'), imagePath: imagePath('531'), generation: 5 },
  { id: '532', name: 'ドッコラー', nameEn: 'Timburr', soundPath: soundPath('532'), imagePath: imagePath('532'), generation: 5 },
  { id: '533', name: 'ドテッコツ', nameEn: 'Gurdurr', soundPath: soundPath('533'), imagePath: imagePath('533'), generation: 5 },
  { id: '534', name: 'ローブシン', nameEn: 'Conkeldurr', soundPath: soundPath('534'), imagePath: imagePath('534'), generation: 5 },
  { id: '535', name: 'オタマロ', nameEn: 'Tympole', soundPath: soundPath('535'), imagePath: imagePath('535'), generation: 5 },
  { id: '536', name: 'ガマガル', nameEn: 'Palpitoad', soundPath: soundPath('536'), imagePath: imagePath('536'), generation: 5 },
  { id: '537', name: 'ガマゲロゲ', nameEn: 'Seismitoad', soundPath: soundPath('537'), imagePath: imagePath('537'), generation: 5 },
  { id: '538', name: 'ナゲキ', nameEn: 'Throh', soundPath: soundPath('538'), imagePath: imagePath('538'), generation: 5 },
  { id: '539', name: 'ダゲキ', nameEn: 'Sawk', soundPath: soundPath('539'), imagePath: imagePath('539'), generation: 5 },
  { id: '540', name: 'クルミル', nameEn: 'Sewaddle', soundPath: soundPath('540'), imagePath: imagePath('540'), generation: 5 },
  { id: '541', name: 'クルマユ', nameEn: 'Swadloon', soundPath: soundPath('541'), imagePath: imagePath('541'), generation: 5 },
  { id: '542', name: 'ハハコモリ', nameEn: 'Leavanny', soundPath: soundPath('542'), imagePath: imagePath('542'), generation: 5 },
  { id: '543', name: 'フシデ', nameEn: 'Venipede', soundPath: soundPath('543'), imagePath: imagePath('543'), generation: 5 },
  { id: '544', name: 'ホイーガ', nameEn: 'Whirlipede', soundPath: soundPath('544'), imagePath: imagePath('544'), generation: 5 },
  { id: '545', name: 'ペンドラー', nameEn: 'Scolipede', soundPath: soundPath('545'), imagePath: imagePath('545'), generation: 5 },
  { id: '546', name: 'モンメン', nameEn: 'Cottonee', soundPath: soundPath('546'), imagePath: imagePath('546'), generation: 5 },
  { id: '547', name: 'エルフーン', nameEn: 'Whimsicott', soundPath: soundPath('547'), imagePath: imagePath('547'), generation: 5 },
  { id: '548', name: 'チュリネ', nameEn: 'Petilil', soundPath: soundPath('548'), imagePath: imagePath('548'), generation: 5 },
  { id: '549', name: 'ドレディア', nameEn: 'Lilligant', soundPath: soundPath('549'), imagePath: imagePath('549'), generation: 5 },
  { id: '550', name: 'バスラオ', nameEn: 'Basculin', soundPath: soundPath('550'), imagePath: imagePath('550'), generation: 5 },
  { id: '551', name: 'メグロコ', nameEn: 'Sandile', soundPath: soundPath('551'), imagePath: imagePath('551'), generation: 5 },
  { id: '552', name: 'ワルビル', nameEn: 'Krokorok', soundPath: soundPath('552'), imagePath: imagePath('552'), generation: 5 },
  { id: '553', name: 'ワルビアル', nameEn: 'Krookodile', soundPath: soundPath('553'), imagePath: imagePath('553'), generation: 5 },
  { id: '554', name: 'ダルマッカ', nameEn: 'Darumaka', soundPath: soundPath('554'), imagePath: imagePath('554'), generation: 5 },
  { id: '555', name: 'ヒヒダルマ', nameEn: 'Darmanitan', soundPath: soundPath('555'), imagePath: imagePath('555'), generation: 5 },
  { id: '556', name: 'マラカッチ', nameEn: 'Maractus', soundPath: soundPath('556'), imagePath: imagePath('556'), generation: 5 },
  { id: '557', name: 'イシズマイ', nameEn: 'Dwebble', soundPath: soundPath('557'), imagePath: imagePath('557'), generation: 5 },
  { id: '558', name: 'イワパレス', nameEn: 'Crustle', soundPath: soundPath('558'), imagePath: imagePath('558'), generation: 5 },
  { id: '559', name: 'ズルッグ', nameEn: 'Scraggy', soundPath: soundPath('559'), imagePath: imagePath('559'), generation: 5 },
  { id: '560', name: 'ズルズキン', nameEn: 'Scrafty', soundPath: soundPath('560'), imagePath: imagePath('560'), generation: 5 },
  { id: '561', name: 'シンボラー', nameEn: 'Sigilyph', soundPath: soundPath('561'), imagePath: imagePath('561'), generation: 5 },
  { id: '562', name: 'デスマス', nameEn: 'Yamask', soundPath: soundPath('562'), imagePath: imagePath('562'), generation: 5 },
  { id: '563', name: 'デスカーン', nameEn: 'Cofagrigus', soundPath: soundPath('563'), imagePath: imagePath('563'), generation: 5 },
  { id: '564', name: 'プロトーガ', nameEn: 'Tirtouga', soundPath: soundPath('564'), imagePath: imagePath('564'), generation: 5 },
  { id: '565', name: 'アバゴーラ', nameEn: 'Carracosta', soundPath: soundPath('565'), imagePath: imagePath('565'), generation: 5 },
  { id: '566', name: 'アーケン', nameEn: 'Archen', soundPath: soundPath('566'), imagePath: imagePath('566'), generation: 5 },
  { id: '567', name: 'アーケオス', nameEn: 'Archeops', soundPath: soundPath('567'), imagePath: imagePath('567'), generation: 5 },
  { id: '568', name: 'ヤブクロン', nameEn: 'Trubbish', soundPath: soundPath('568'), imagePath: imagePath('568'), generation: 5 },
  { id: '569', name: 'ダストダス', nameEn: 'Garbodor', soundPath: soundPath('569'), imagePath: imagePath('569'), generation: 5 },
  { id: '570', name: 'ゾロア', nameEn: 'Zorua', soundPath: soundPath('570'), imagePath: imagePath('570'), generation: 5 },
  { id: '571', name: 'ゾロアーク', nameEn: 'Zoroark', soundPath: soundPath('571'), imagePath: imagePath('571'), generation: 5 },
  { id: '572', name: 'チラーミィ', nameEn: 'Minccino', soundPath: soundPath('572'), imagePath: imagePath('572'), generation: 5 },
  { id: '573', name: 'チラチーノ', nameEn: 'Cinccino', soundPath: soundPath('573'), imagePath: imagePath('573'), generation: 5 },
  { id: '574', name: 'ゴチム', nameEn: 'Gothita', soundPath: soundPath('574'), imagePath: imagePath('574'), generation: 5 },
  { id: '575', name: 'ゴチミル', nameEn: 'Gothorita', soundPath: soundPath('575'), imagePath: imagePath('575'), generation: 5 },
  { id: '576', name: 'ゴチルゼル', nameEn: 'Gothitelle', soundPath: soundPath('576'), imagePath: imagePath('576'), generation: 5 },
  { id: '577', name: 'ユニラン', nameEn: 'Solosis', soundPath: soundPath('577'), imagePath: imagePath('577'), generation: 5 },
  { id: '578', name: 'ダブラン', nameEn: 'Duosion', soundPath: soundPath('578'), imagePath: imagePath('578'), generation: 5 },
  { id: '579', name: 'ランクルス', nameEn: 'Reuniclus', soundPath: soundPath('579'), imagePath: imagePath('579'), generation: 5 },
  { id: '580', name: 'コアルヒー', nameEn: 'Ducklett', soundPath: soundPath('580'), imagePath: imagePath('580'), generation: 5 },
  { id: '581', name: 'スワンナ', nameEn: 'Swanna', soundPath: soundPath('581'), imagePath: imagePath('581'), generation: 5 },
  { id: '582', name: 'バニプッチ', nameEn: 'Vanillite', soundPath: soundPath('582'), imagePath: imagePath('582'), generation: 5 },
  { id: '583', name: 'バニリッチ', nameEn: 'Vanillish', soundPath: soundPath('583'), imagePath: imagePath('583'), generation: 5 },
  { id: '584', name: 'バイバニラ', nameEn: 'Vanilluxe', soundPath: soundPath('584'), imagePath: imagePath('584'), generation: 5 },
  { id: '585', name: 'シキジカ', nameEn: 'Deerling', soundPath: soundPath('585'), imagePath: imagePath('585'), generation: 5 },
  { id: '586', name: 'メブキジカ', nameEn: 'Sawsbuck', soundPath: soundPath('586'), imagePath: imagePath('586'), generation: 5 },
  { id: '587', name: 'エモンガ', nameEn: 'Emolga', soundPath: soundPath('587'), imagePath: imagePath('587'), generation: 5 },
  { id: '588', name: 'カブルモ', nameEn: 'Karrablast', soundPath: soundPath('588'), imagePath: imagePath('588'), generation: 5 },
  { id: '589', name: 'シュバルゴ', nameEn: 'Escavalier', soundPath: soundPath('589'), imagePath: imagePath('589'), generation: 5 },
  { id: '590', name: 'タマゲタケ', nameEn: 'Foongus', soundPath: soundPath('590'), imagePath: imagePath('590'), generation: 5 },
  { id: '591', name: 'モロバレル', nameEn: 'Amoonguss', soundPath: soundPath('591'), imagePath: imagePath('591'), generation: 5 },
  { id: '592', name: 'プルリル', nameEn: 'Frillish', soundPath: soundPath('592'), imagePath: imagePath('592'), generation: 5 },
  { id: '593', name: 'ブルンゲル', nameEn: 'Jellicent', soundPath: soundPath('593'), imagePath: imagePath('593'), generation: 5 },
  { id: '594', name: 'ママンボウ', nameEn: 'Alomomola', soundPath: soundPath('594'), imagePath: imagePath('594'), generation: 5 },
  { id: '595', name: 'バチュル', nameEn: 'Joltik', soundPath: soundPath('595'), imagePath: imagePath('595'), generation: 5 },
  { id: '596', name: 'デンチュラ', nameEn: 'Galvantula', soundPath: soundPath('596'), imagePath: imagePath('596'), generation: 5 },
  { id: '597', name: 'テッシード', nameEn: 'Ferroseed', soundPath: soundPath('597'), imagePath: imagePath('597'), generation: 5 },
  { id: '598', name: 'ナットレイ', nameEn: 'Ferrothorn', soundPath: soundPath('598'), imagePath: imagePath('598'), generation: 5 },
  { id: '599', name: 'ギアル', nameEn: 'Klink', soundPath: soundPath('599'), imagePath: imagePath('599'), generation: 5 },
  { id: '600', name: 'ギギアル', nameEn: 'Klang', soundPath: soundPath('600'), imagePath: imagePath('600'), generation: 5 },
  { id: '601', name: 'ギギギアル', nameEn: 'Klinklang', soundPath: soundPath('601'), imagePath: imagePath('601'), generation: 5 },
  { id: '602', name: 'シビシラス', nameEn: 'Tynamo', soundPath: soundPath('602'), imagePath: imagePath('602'), generation: 5 },
  { id: '603', name: 'シビビール', nameEn: 'Eelektrik', soundPath: soundPath('603'), imagePath: imagePath('603'), generation: 5 },
  { id: '604', name: 'シビルドン', nameEn: 'Eelektross', soundPath: soundPath('604'), imagePath: imagePath('604'), generation: 5 },
  { id: '605', name: 'リグレー', nameEn: 'Elgyem', soundPath: soundPath('605'), imagePath: imagePath('605'), generation: 5 },
  { id: '606', name: 'オーベム', nameEn: 'Beheeyem', soundPath: soundPath('606'), imagePath: imagePath('606'), generation: 5 },
  { id: '607', name: 'ヒトモシ', nameEn: 'Litwick', soundPath: soundPath('607'), imagePath: imagePath('607'), generation: 5 },
  { id: '608', name: 'ランプラー', nameEn: 'Lampent', soundPath: soundPath('608'), imagePath: imagePath('608'), generation: 5 },
  { id: '609', name: 'シャンデラ', nameEn: 'Chandelure', soundPath: soundPath('609'), imagePath: imagePath('609'), generation: 5 },
  { id: '610', name: 'キバゴ', nameEn: 'Axew', soundPath: soundPath('610'), imagePath: imagePath('610'), generation: 5 },
  { id: '611', name: 'オノンド', nameEn: 'Fraxure', soundPath: soundPath('611'), imagePath: imagePath('611'), generation: 5 },
  { id: '612', name: 'オノノクス', nameEn: 'Haxorus', soundPath: soundPath('612'), imagePath: imagePath('612'), generation: 5 },
  { id: '613', name: 'クマシュン', nameEn: 'Cubchoo', soundPath: soundPath('613'), imagePath: imagePath('613'), generation: 5 },
  { id: '614', name: 'ツンベアー', nameEn: 'Beartic', soundPath: soundPath('614'), imagePath: imagePath('614'), generation: 5 },
  { id: '615', name: 'フリージオ', nameEn: 'Cryogonal', soundPath: soundPath('615'), imagePath: imagePath('615'), generation: 5 },
  { id: '616', name: 'チョボマキ', nameEn: 'Shelmet', soundPath: soundPath('616'), imagePath: imagePath('616'), generation: 5 },
  { id: '617', name: 'アギルダー', nameEn: 'Accelgor', soundPath: soundPath('617'), imagePath: imagePath('617'), generation: 5 },
  { id: '618', name: 'マッギョ', nameEn: 'Stunfisk', soundPath: soundPath('618'), imagePath: imagePath('618'), generation: 5 },
  { id: '619', name: 'コジョフー', nameEn: 'Mienfoo', soundPath: soundPath('619'), imagePath: imagePath('619'), generation: 5 },
  { id: '620', name: 'コジョンド', nameEn: 'Mienshao', soundPath: soundPath('620'), imagePath: imagePath('620'), generation: 5 },
  { id: '621', name: 'クリムガン', nameEn: 'Druddigon', soundPath: soundPath('621'), imagePath: imagePath('621'), generation: 5 },
  { id: '622', name: 'ゴビット', nameEn: 'Golett', soundPath: soundPath('622'), imagePath: imagePath('622'), generation: 5 },
  { id: '623', name: 'ゴルーグ', nameEn: 'Golurk', soundPath: soundPath('623'), imagePath: imagePath('623'), generation: 5 },
  { id: '624', name: 'コマタナ', nameEn: 'Pawniard', soundPath: soundPath('624'), imagePath: imagePath('624'), generation: 5 },
  { id: '625', name: 'キリキザン', nameEn: 'Bisharp', soundPath: soundPath('625'), imagePath: imagePath('625'), generation: 5 },
  { id: '626', name: 'バッフロン', nameEn: 'Bouffalant', soundPath: soundPath('626'), imagePath: imagePath('626'), generation: 5 },
  { id: '627', name: 'ワシボン', nameEn: 'Rufflet', soundPath: soundPath('627'), imagePath: imagePath('627'), generation: 5 },
  { id: '628', name: 'ウォーグル', nameEn: 'Braviary', soundPath: soundPath('628'), imagePath: imagePath('628'), generation: 5 },
  { id: '629', name: 'バルチャイ', nameEn: 'Vullaby', soundPath: soundPath('629'), imagePath: imagePath('629'), generation: 5 },
  { id: '630', name: 'バルジーナ', nameEn: 'Mandibuzz', soundPath: soundPath('630'), imagePath: imagePath('630'), generation: 5 },
  { id: '631', name: 'クイタラン', nameEn: 'Heatmor', soundPath: soundPath('631'), imagePath: imagePath('631'), generation: 5 },
  { id: '632', name: 'アイアント', nameEn: 'Durant', soundPath: soundPath('632'), imagePath: imagePath('632'), generation: 5 },
  { id: '633', name: 'モノズ', nameEn: 'Deino', soundPath: soundPath('633'), imagePath: imagePath('633'), generation: 5 },
  { id: '634', name: 'ジヘッド', nameEn: 'Zweilous', soundPath: soundPath('634'), imagePath: imagePath('634'), generation: 5 },
  { id: '635', name: 'サザンドラ', nameEn: 'Hydreigon', soundPath: soundPath('635'), imagePath: imagePath('635'), generation: 5 },
  { id: '636', name: 'メラルバ', nameEn: 'Larvesta', soundPath: soundPath('636'), imagePath: imagePath('636'), generation: 5 },
  { id: '637', name: 'ウルガモス', nameEn: 'Volcarona', soundPath: soundPath('637'), imagePath: imagePath('637'), generation: 5 },
  { id: '638', name: 'コバルオン', nameEn: 'Cobalion', soundPath: soundPath('638'), imagePath: imagePath('638'), generation: 5 },
  { id: '639', name: 'テラキオン', nameEn: 'Terrakion', soundPath: soundPath('639'), imagePath: imagePath('639'), generation: 5 },
  { id: '640', name: 'ビリジオン', nameEn: 'Virizion', soundPath: soundPath('640'), imagePath: imagePath('640'), generation: 5 },
  { id: '641', name: 'トルネロス', nameEn: 'Tornadus', soundPath: soundPath('641'), imagePath: imagePath('641'), generation: 5 },
  { id: '642', name: 'ボルトロス', nameEn: 'Thundurus', soundPath: soundPath('642'), imagePath: imagePath('642'), generation: 5 },
  { id: '643', name: 'レシラム', nameEn: 'Reshiram', soundPath: soundPath('643'), imagePath: imagePath('643'), generation: 5 },
  { id: '644', name: 'ゼクロム', nameEn: 'Zekrom', soundPath: soundPath('644'), imagePath: imagePath('644'), generation: 5 },
  { id: '645', name: 'ランドロス', nameEn: 'Landorus', soundPath: soundPath('645'), imagePath: imagePath('645'), generation: 5 },
  { id: '646', name: 'キュレム', nameEn: 'Kyurem', soundPath: soundPath('646'), imagePath: imagePath('646'), generation: 5 },
  { id: '647', name: 'ケルディオ', nameEn: 'Keldeo', soundPath: soundPath('647'), imagePath: imagePath('647'), generation: 5 },
  { id: '648', name: 'メロエッタ', nameEn: 'Meloetta', soundPath: soundPath('648'), imagePath: imagePath('648'), generation: 5 },
  { id: '649', name: 'ゲノセクト', nameEn: 'Genesect', soundPath: soundPath('649'), imagePath: imagePath('649'), generation: 5 },
];

export function getGenerationById(id: number): GenerationInfo | undefined {
  return GENERATIONS.find(g => g.id === id);
}

function normalizeGenerations(generations?: number | number[]): number[] {
  if (generations === undefined) return [];
  return Array.isArray(generations) ? generations : [generations];
}

export function getPokemonListByGenerations(generations: number[]): Pokemon[] {
  if (generations.length === 0) return POKEMON_LIST;
  return POKEMON_LIST.filter(p => generations.includes(p.generation));
}

export function getRandomPokemon(generations?: number | number[]): Pokemon {
  const pool = getPokemonListByGenerations(normalizeGenerations(generations));
  return pool[Math.floor(Math.random() * pool.length)];
}

export function getRandomPokemons(count: number, excludeId?: string, generations?: number | number[]): Pokemon[] {
  const pool = getPokemonListByGenerations(normalizeGenerations(generations)).filter(p => p.id !== excludeId);
  return shuffleArray(pool).slice(0, count);
}

export function getPokemonById(id: string): Pokemon | undefined {
  return POKEMON_LIST.find(p => p.id === id);
}

export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
